-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct_Loop_Xpose_Col_Outer_Loop_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    col_outbuf_i_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    col_outbuf_i_ce0 : OUT STD_LOGIC;
    col_outbuf_i_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    buf_2d_out_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf_2d_out_ce0 : OUT STD_LOGIC;
    buf_2d_out_we0 : OUT STD_LOGIC;
    buf_2d_out_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dct_Loop_Xpose_Col_Outer_Loop_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_pp0_stg0_fsm_1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_st4_fsm_2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_21 : BOOLEAN;
    signal indvar_flatten_reg_71 : STD_LOGIC_VECTOR (6 downto 0);
    signal j_1_i_reg_82 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_3_i_reg_93 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond_flatten_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten_reg_202 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_pp0_stg0_fsm_1 : STD_LOGIC;
    signal ap_sig_54 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal indvar_flatten_next_fu_110_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_3_i_mid2_fu_128_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_3_i_mid2_reg_211 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_mid2_v_fu_136_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_mid2_v_reg_216 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_171_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_78 : BOOLEAN;
    signal j_1_i_phi_fu_86_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_15_cast_fu_166_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_16_cast_fu_197_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal exitcond_i2_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_116_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_148_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_1_mid2_cast_fu_144_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_cast_fu_156_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_160_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_177_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_2_cast_fu_188_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_cast_fu_184_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_191_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_2 : STD_LOGIC;
    signal ap_sig_163 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_2)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and not((exitcond_flatten_fu_104_p2 = ap_const_lv1_0)))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_78))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (exitcond_flatten_fu_104_p2 = ap_const_lv1_0))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_78)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and not((exitcond_flatten_fu_104_p2 = ap_const_lv1_0))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_3_i_reg_93_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (exitcond_flatten_fu_104_p2 = ap_const_lv1_0))) then 
                i_3_i_reg_93 <= i_fu_171_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_78))) then 
                i_3_i_reg_93 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_71_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (exitcond_flatten_fu_104_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_71 <= indvar_flatten_next_fu_110_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_78))) then 
                indvar_flatten_reg_71 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    j_1_i_reg_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond_flatten_reg_202 = ap_const_lv1_0))) then 
                j_1_i_reg_82 <= tmp_1_mid2_v_reg_216;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_78))) then 
                j_1_i_reg_82 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1)) then
                exitcond_flatten_reg_202 <= exitcond_flatten_fu_104_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (exitcond_flatten_fu_104_p2 = ap_const_lv1_0))) then
                i_3_i_mid2_reg_211 <= i_3_i_mid2_fu_128_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (exitcond_flatten_fu_104_p2 = ap_const_lv1_0))) then
                tmp_1_mid2_v_reg_216 <= tmp_1_mid2_v_fu_136_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, exitcond_flatten_fu_104_p2, ap_reg_ppiten_pp0_it0, ap_sig_78)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_78)) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_pp0_stg0_fsm_1 => 
                if (not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((exitcond_flatten_fu_104_p2 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st4_fsm_2;
                end if;
            when ap_ST_st4_fsm_2 => 
                ap_NS_fsm <= ap_ST_st1_fsm_0;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    ap_done_assign_proc : process(ap_done_reg, ap_sig_cseq_ST_st4_fsm_2)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or (ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_sig_cseq_ST_st4_fsm_2)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_163_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_163 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_21_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_21 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_54_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_54 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_78_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_78 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_sig_cseq_ST_pp0_stg0_fsm_1_assign_proc : process(ap_sig_54)
    begin
        if (ap_sig_54) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_21)
    begin
        if (ap_sig_21) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st4_fsm_2_assign_proc : process(ap_sig_163)
    begin
        if (ap_sig_163) then 
            ap_sig_cseq_ST_st4_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;

    buf_2d_out_address0 <= tmp_16_cast_fu_197_p1(6 - 1 downto 0);

    buf_2d_out_ce0_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            buf_2d_out_ce0 <= ap_const_logic_1;
        else 
            buf_2d_out_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_2d_out_d0 <= col_outbuf_i_q0;

    buf_2d_out_we0_assign_proc : process(exitcond_flatten_reg_202, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it1)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond_flatten_reg_202 = ap_const_lv1_0)))) then 
            buf_2d_out_we0 <= ap_const_logic_1;
        else 
            buf_2d_out_we0 <= ap_const_logic_0;
        end if; 
    end process;

    col_outbuf_i_address0 <= tmp_15_cast_fu_166_p1(6 - 1 downto 0);

    col_outbuf_i_ce0_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it0)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0))) then 
            col_outbuf_i_ce0 <= ap_const_logic_1;
        else 
            col_outbuf_i_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    exitcond_flatten_fu_104_p2 <= "1" when (indvar_flatten_reg_71 = ap_const_lv7_40) else "0";
    exitcond_i2_fu_122_p2 <= "1" when (i_3_i_reg_93 = ap_const_lv4_8) else "0";
    i_3_i_mid2_fu_128_p3 <= 
        ap_const_lv4_0 when (exitcond_i2_fu_122_p2(0) = '1') else 
        i_3_i_reg_93;
    i_fu_171_p2 <= std_logic_vector(unsigned(i_3_i_mid2_fu_128_p3) + unsigned(ap_const_lv4_1));
    indvar_flatten_next_fu_110_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_71) + unsigned(ap_const_lv7_1));

    j_1_i_phi_fu_86_p4_assign_proc : process(j_1_i_reg_82, exitcond_flatten_reg_202, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it1, tmp_1_mid2_v_reg_216)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (exitcond_flatten_reg_202 = ap_const_lv1_0))) then 
            j_1_i_phi_fu_86_p4 <= tmp_1_mid2_v_reg_216;
        else 
            j_1_i_phi_fu_86_p4 <= j_1_i_reg_82;
        end if; 
    end process;

    j_fu_116_p2 <= std_logic_vector(unsigned(j_1_i_phi_fu_86_p4) + unsigned(ap_const_lv4_1));
    tmp_12_cast_fu_184_p1 <= std_logic_vector(resize(unsigned(tmp_fu_177_p3),8));
    tmp_14_cast_fu_156_p1 <= std_logic_vector(resize(unsigned(tmp_s_fu_148_p3),8));
    tmp_15_cast_fu_166_p1 <= std_logic_vector(resize(unsigned(tmp_1_fu_160_p2),64));
    tmp_16_cast_fu_197_p1 <= std_logic_vector(resize(unsigned(tmp_2_fu_191_p2),64));
    tmp_1_fu_160_p2 <= std_logic_vector(unsigned(tmp_1_mid2_cast_fu_144_p1) + unsigned(tmp_14_cast_fu_156_p1));
    tmp_1_mid2_cast_fu_144_p1 <= std_logic_vector(resize(unsigned(tmp_1_mid2_v_fu_136_p3),8));
    tmp_1_mid2_v_fu_136_p3 <= 
        j_fu_116_p2 when (exitcond_i2_fu_122_p2(0) = '1') else 
        j_1_i_phi_fu_86_p4;
    tmp_2_cast_fu_188_p1 <= std_logic_vector(resize(unsigned(i_3_i_mid2_reg_211),8));
    tmp_2_fu_191_p2 <= std_logic_vector(unsigned(tmp_2_cast_fu_188_p1) + unsigned(tmp_12_cast_fu_184_p1));
    tmp_fu_177_p3 <= (tmp_1_mid2_v_reg_216 & ap_const_lv3_0);
    tmp_s_fu_148_p3 <= (i_3_i_mid2_fu_128_p3 & ap_const_lv3_0);
end behav;
