// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dct.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dct::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<6> dct::ap_const_lv6_0 = "000000";
const sc_logic dct::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> dct::ap_const_lv16_0 = "0000000000000000";
const sc_lv<128> dct::ap_const_lv128_lc_2 = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const bool dct::ap_true = true;

dct::dct(sc_module_name name) : sc_module(name), mVcdFile(0) {
    row_outbuf_i_U = new dct_row_outbuf_i("row_outbuf_i_U");
    row_outbuf_i_U->clk(ap_clk);
    row_outbuf_i_U->reset(ap_rst);
    row_outbuf_i_U->i_address0(dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_address0);
    row_outbuf_i_U->i_ce0(dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_ce0);
    row_outbuf_i_U->i_we0(dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_we0);
    row_outbuf_i_U->i_d0(dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_d0);
    row_outbuf_i_U->i_q0(row_outbuf_i_i_q0);
    row_outbuf_i_U->t_address0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_address0);
    row_outbuf_i_U->t_ce0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_ce0);
    row_outbuf_i_U->t_we0(ap_var_for_const0);
    row_outbuf_i_U->t_d0(ap_var_for_const1);
    row_outbuf_i_U->t_q0(row_outbuf_i_t_q0);
    row_outbuf_i_U->i_ce(ap_var_for_const2);
    row_outbuf_i_U->t_ce(ap_var_for_const2);
    row_outbuf_i_U->i_full_n(row_outbuf_i_i_full_n);
    row_outbuf_i_U->i_write(dct_Loop_Row_DCT_Loop_proc_U0_ap_done);
    row_outbuf_i_U->t_empty_n(row_outbuf_i_t_empty_n);
    row_outbuf_i_U->t_read(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready);
    col_outbuf_i_U = new dct_row_outbuf_i("col_outbuf_i_U");
    col_outbuf_i_U->clk(ap_clk);
    col_outbuf_i_U->reset(ap_rst);
    col_outbuf_i_U->i_address0(dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_address0);
    col_outbuf_i_U->i_ce0(dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_ce0);
    col_outbuf_i_U->i_we0(dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_we0);
    col_outbuf_i_U->i_d0(dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_d0);
    col_outbuf_i_U->i_q0(col_outbuf_i_i_q0);
    col_outbuf_i_U->t_address0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_address0);
    col_outbuf_i_U->t_ce0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_ce0);
    col_outbuf_i_U->t_we0(ap_var_for_const0);
    col_outbuf_i_U->t_d0(ap_var_for_const1);
    col_outbuf_i_U->t_q0(col_outbuf_i_t_q0);
    col_outbuf_i_U->i_ce(ap_var_for_const2);
    col_outbuf_i_U->t_ce(ap_var_for_const2);
    col_outbuf_i_U->i_full_n(col_outbuf_i_i_full_n);
    col_outbuf_i_U->i_write(dct_Loop_Col_DCT_Loop_proc_U0_ap_done);
    col_outbuf_i_U->t_empty_n(col_outbuf_i_t_empty_n);
    col_outbuf_i_U->t_read(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready);
    col_inbuf_U = new dct_col_inbuf("col_inbuf_U");
    col_inbuf_U->clk(ap_clk);
    col_inbuf_U->reset(ap_rst);
    col_inbuf_U->i_address0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_address0);
    col_inbuf_U->i_ce0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_ce0);
    col_inbuf_U->i_we0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_we0);
    col_inbuf_U->i_d0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_d0);
    col_inbuf_U->i_q0(col_inbuf_i_q0);
    col_inbuf_U->t_address0(dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_address0);
    col_inbuf_U->t_ce0(dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_ce0);
    col_inbuf_U->t_we0(ap_var_for_const0);
    col_inbuf_U->t_d0(ap_var_for_const3);
    col_inbuf_U->t_q0(col_inbuf_t_q0);
    col_inbuf_U->i_ce(ap_var_for_const2);
    col_inbuf_U->t_ce(ap_var_for_const2);
    col_inbuf_U->i_full_n(col_inbuf_i_full_n);
    col_inbuf_U->i_write(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done);
    col_inbuf_U->t_empty_n(col_inbuf_t_empty_n);
    col_inbuf_U->t_read(dct_Loop_Col_DCT_Loop_proc_U0_ap_ready);
    buf_2d_in_U = new dct_col_inbuf("buf_2d_in_U");
    buf_2d_in_U->clk(ap_clk);
    buf_2d_in_U->reset(ap_rst);
    buf_2d_in_U->i_address0(dct_read_data_U0_buf_r_address0);
    buf_2d_in_U->i_ce0(dct_read_data_U0_buf_r_ce0);
    buf_2d_in_U->i_we0(dct_read_data_U0_buf_r_we0);
    buf_2d_in_U->i_d0(dct_read_data_U0_buf_r_d0);
    buf_2d_in_U->i_q0(buf_2d_in_i_q0);
    buf_2d_in_U->t_address0(dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_address0);
    buf_2d_in_U->t_ce0(dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_ce0);
    buf_2d_in_U->t_we0(ap_var_for_const0);
    buf_2d_in_U->t_d0(ap_var_for_const3);
    buf_2d_in_U->t_q0(buf_2d_in_t_q0);
    buf_2d_in_U->i_ce(ap_var_for_const2);
    buf_2d_in_U->t_ce(ap_var_for_const2);
    buf_2d_in_U->i_full_n(buf_2d_in_i_full_n);
    buf_2d_in_U->i_write(dct_read_data_U0_ap_done);
    buf_2d_in_U->t_empty_n(buf_2d_in_t_empty_n);
    buf_2d_in_U->t_read(dct_Loop_Row_DCT_Loop_proc_U0_ap_ready);
    buf_2d_out_U = new dct_row_outbuf_i("buf_2d_out_U");
    buf_2d_out_U->clk(ap_clk);
    buf_2d_out_U->reset(ap_rst);
    buf_2d_out_U->i_address0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_address0);
    buf_2d_out_U->i_ce0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_ce0);
    buf_2d_out_U->i_we0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_we0);
    buf_2d_out_U->i_d0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_d0);
    buf_2d_out_U->i_q0(buf_2d_out_i_q0);
    buf_2d_out_U->t_address0(dct_write_data_U0_buf_r_address0);
    buf_2d_out_U->t_ce0(dct_write_data_U0_buf_r_ce0);
    buf_2d_out_U->t_we0(ap_var_for_const0);
    buf_2d_out_U->t_d0(ap_var_for_const1);
    buf_2d_out_U->t_q0(buf_2d_out_t_q0);
    buf_2d_out_U->i_ce(ap_var_for_const2);
    buf_2d_out_U->t_ce(ap_var_for_const2);
    buf_2d_out_U->i_full_n(buf_2d_out_i_full_n);
    buf_2d_out_U->i_write(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done);
    buf_2d_out_U->t_empty_n(buf_2d_out_t_empty_n);
    buf_2d_out_U->t_read(dct_write_data_U0_ap_ready);
    dct_read_data_U0 = new dct_read_data("dct_read_data_U0");
    dct_read_data_U0->ap_clk(ap_clk);
    dct_read_data_U0->ap_rst(ap_rst);
    dct_read_data_U0->ap_start(dct_read_data_U0_ap_start);
    dct_read_data_U0->ap_done(dct_read_data_U0_ap_done);
    dct_read_data_U0->ap_continue(dct_read_data_U0_ap_continue);
    dct_read_data_U0->ap_idle(dct_read_data_U0_ap_idle);
    dct_read_data_U0->ap_ready(dct_read_data_U0_ap_ready);
    dct_read_data_U0->input_r_address0(dct_read_data_U0_input_r_address0);
    dct_read_data_U0->input_r_ce0(dct_read_data_U0_input_r_ce0);
    dct_read_data_U0->input_r_q0(input_r_q0);
    dct_read_data_U0->buf_r_address0(dct_read_data_U0_buf_r_address0);
    dct_read_data_U0->buf_r_ce0(dct_read_data_U0_buf_r_ce0);
    dct_read_data_U0->buf_r_we0(dct_read_data_U0_buf_r_we0);
    dct_read_data_U0->buf_r_d0(dct_read_data_U0_buf_r_d0);
    dct_read_data_U0->buf_r_q0(buf_2d_in_i_q0);
    dct_Loop_Row_DCT_Loop_proc_U0 = new dct_Loop_Row_DCT_Loop_proc("dct_Loop_Row_DCT_Loop_proc_U0");
    dct_Loop_Row_DCT_Loop_proc_U0->ap_clk(ap_clk);
    dct_Loop_Row_DCT_Loop_proc_U0->ap_rst(ap_rst);
    dct_Loop_Row_DCT_Loop_proc_U0->ap_start(dct_Loop_Row_DCT_Loop_proc_U0_ap_start);
    dct_Loop_Row_DCT_Loop_proc_U0->ap_done(dct_Loop_Row_DCT_Loop_proc_U0_ap_done);
    dct_Loop_Row_DCT_Loop_proc_U0->ap_continue(dct_Loop_Row_DCT_Loop_proc_U0_ap_continue);
    dct_Loop_Row_DCT_Loop_proc_U0->ap_idle(dct_Loop_Row_DCT_Loop_proc_U0_ap_idle);
    dct_Loop_Row_DCT_Loop_proc_U0->ap_ready(dct_Loop_Row_DCT_Loop_proc_U0_ap_ready);
    dct_Loop_Row_DCT_Loop_proc_U0->buf_2d_in_address0(dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_address0);
    dct_Loop_Row_DCT_Loop_proc_U0->buf_2d_in_ce0(dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_ce0);
    dct_Loop_Row_DCT_Loop_proc_U0->buf_2d_in_q0(buf_2d_in_t_q0);
    dct_Loop_Row_DCT_Loop_proc_U0->row_outbuf_i_address0(dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_address0);
    dct_Loop_Row_DCT_Loop_proc_U0->row_outbuf_i_ce0(dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_ce0);
    dct_Loop_Row_DCT_Loop_proc_U0->row_outbuf_i_we0(dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_we0);
    dct_Loop_Row_DCT_Loop_proc_U0->row_outbuf_i_d0(dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_d0);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0 = new dct_Loop_Xpose_Row_Outer_Loop_proc("dct_Loop_Xpose_Row_Outer_Loop_proc_U0");
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->ap_clk(ap_clk);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->ap_rst(ap_rst);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->ap_start(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->ap_done(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->ap_continue(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->ap_idle(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_idle);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->ap_ready(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->row_outbuf_i_address0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_address0);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->row_outbuf_i_ce0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_ce0);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->row_outbuf_i_q0(row_outbuf_i_t_q0);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->col_inbuf_address0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_address0);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->col_inbuf_ce0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_ce0);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->col_inbuf_we0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_we0);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->col_inbuf_d0(dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_d0);
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0->col_inbuf_q0(col_inbuf_i_q0);
    dct_Loop_Col_DCT_Loop_proc_U0 = new dct_Loop_Col_DCT_Loop_proc("dct_Loop_Col_DCT_Loop_proc_U0");
    dct_Loop_Col_DCT_Loop_proc_U0->ap_clk(ap_clk);
    dct_Loop_Col_DCT_Loop_proc_U0->ap_rst(ap_rst);
    dct_Loop_Col_DCT_Loop_proc_U0->ap_start(dct_Loop_Col_DCT_Loop_proc_U0_ap_start);
    dct_Loop_Col_DCT_Loop_proc_U0->ap_done(dct_Loop_Col_DCT_Loop_proc_U0_ap_done);
    dct_Loop_Col_DCT_Loop_proc_U0->ap_continue(dct_Loop_Col_DCT_Loop_proc_U0_ap_continue);
    dct_Loop_Col_DCT_Loop_proc_U0->ap_idle(dct_Loop_Col_DCT_Loop_proc_U0_ap_idle);
    dct_Loop_Col_DCT_Loop_proc_U0->ap_ready(dct_Loop_Col_DCT_Loop_proc_U0_ap_ready);
    dct_Loop_Col_DCT_Loop_proc_U0->col_inbuf_address0(dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_address0);
    dct_Loop_Col_DCT_Loop_proc_U0->col_inbuf_ce0(dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_ce0);
    dct_Loop_Col_DCT_Loop_proc_U0->col_inbuf_q0(col_inbuf_t_q0);
    dct_Loop_Col_DCT_Loop_proc_U0->col_outbuf_i_address0(dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_address0);
    dct_Loop_Col_DCT_Loop_proc_U0->col_outbuf_i_ce0(dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_ce0);
    dct_Loop_Col_DCT_Loop_proc_U0->col_outbuf_i_we0(dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_we0);
    dct_Loop_Col_DCT_Loop_proc_U0->col_outbuf_i_d0(dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_d0);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0 = new dct_Loop_Xpose_Col_Outer_Loop_proc("dct_Loop_Xpose_Col_Outer_Loop_proc_U0");
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->ap_clk(ap_clk);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->ap_rst(ap_rst);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->ap_start(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->ap_done(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->ap_continue(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->ap_idle(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_idle);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->ap_ready(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->col_outbuf_i_address0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_address0);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->col_outbuf_i_ce0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_ce0);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->col_outbuf_i_q0(col_outbuf_i_t_q0);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->buf_2d_out_address0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_address0);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->buf_2d_out_ce0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_ce0);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->buf_2d_out_we0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_we0);
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0->buf_2d_out_d0(dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_d0);
    dct_write_data_U0 = new dct_write_data("dct_write_data_U0");
    dct_write_data_U0->ap_clk(ap_clk);
    dct_write_data_U0->ap_rst(ap_rst);
    dct_write_data_U0->ap_start(dct_write_data_U0_ap_start);
    dct_write_data_U0->ap_done(dct_write_data_U0_ap_done);
    dct_write_data_U0->ap_continue(dct_write_data_U0_ap_continue);
    dct_write_data_U0->ap_idle(dct_write_data_U0_ap_idle);
    dct_write_data_U0->ap_ready(dct_write_data_U0_ap_ready);
    dct_write_data_U0->buf_r_address0(dct_write_data_U0_buf_r_address0);
    dct_write_data_U0->buf_r_ce0(dct_write_data_U0_buf_r_ce0);
    dct_write_data_U0->buf_r_q0(buf_2d_out_t_q0);
    dct_write_data_U0->output_r_address0(dct_write_data_U0_output_r_address0);
    dct_write_data_U0->output_r_ce0(dct_write_data_U0_output_r_ce0);
    dct_write_data_U0->output_r_we0(dct_write_data_U0_output_r_we0);
    dct_write_data_U0->output_r_d0(dct_write_data_U0_output_r_d0);

    SC_METHOD(thread_ap_chn_write_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i);
    sensitive << ( dct_Loop_Col_DCT_Loop_proc_U0_ap_done );

    SC_METHOD(thread_ap_chn_write_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i);
    sensitive << ( dct_Loop_Row_DCT_Loop_proc_U0_ap_done );

    SC_METHOD(thread_ap_chn_write_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out);
    sensitive << ( dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done );

    SC_METHOD(thread_ap_chn_write_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf);
    sensitive << ( dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done );

    SC_METHOD(thread_ap_chn_write_dct_read_data_U0_buf_2d_in);
    sensitive << ( dct_read_data_U0_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_hs_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( dct_read_data_U0_ap_idle );
    sensitive << ( dct_Loop_Row_DCT_Loop_proc_U0_ap_idle );
    sensitive << ( dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_idle );
    sensitive << ( dct_Loop_Col_DCT_Loop_proc_U0_ap_idle );
    sensitive << ( dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_idle );
    sensitive << ( dct_write_data_U0_ap_idle );
    sensitive << ( buf_2d_in_t_empty_n );
    sensitive << ( row_outbuf_i_t_empty_n );
    sensitive << ( col_inbuf_t_empty_n );
    sensitive << ( col_outbuf_i_t_empty_n );
    sensitive << ( buf_2d_out_t_empty_n );

    SC_METHOD(thread_ap_ready);
    sensitive << ( dct_read_data_U0_ap_ready );

    SC_METHOD(thread_ap_sig_hs_continue);

    SC_METHOD(thread_ap_sig_hs_done);
    sensitive << ( dct_write_data_U0_ap_done );

    SC_METHOD(thread_ap_sig_hs_ready);
    sensitive << ( dct_read_data_U0_ap_ready );

    SC_METHOD(thread_dct_Loop_Col_DCT_Loop_proc_U0_ap_continue);
    sensitive << ( col_outbuf_i_i_full_n );

    SC_METHOD(thread_dct_Loop_Col_DCT_Loop_proc_U0_ap_start);
    sensitive << ( col_inbuf_t_empty_n );

    SC_METHOD(thread_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_pipo_status);
    sensitive << ( col_outbuf_i_i_full_n );

    SC_METHOD(thread_dct_Loop_Row_DCT_Loop_proc_U0_ap_continue);
    sensitive << ( row_outbuf_i_i_full_n );

    SC_METHOD(thread_dct_Loop_Row_DCT_Loop_proc_U0_ap_start);
    sensitive << ( buf_2d_in_t_empty_n );

    SC_METHOD(thread_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_pipo_status);
    sensitive << ( row_outbuf_i_i_full_n );

    SC_METHOD(thread_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue);
    sensitive << ( buf_2d_out_i_full_n );

    SC_METHOD(thread_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start);
    sensitive << ( col_outbuf_i_t_empty_n );

    SC_METHOD(thread_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_pipo_status);
    sensitive << ( buf_2d_out_i_full_n );

    SC_METHOD(thread_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue);
    sensitive << ( col_inbuf_i_full_n );

    SC_METHOD(thread_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start);
    sensitive << ( row_outbuf_i_t_empty_n );

    SC_METHOD(thread_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_pipo_status);
    sensitive << ( col_inbuf_i_full_n );

    SC_METHOD(thread_dct_read_data_U0_ap_continue);
    sensitive << ( buf_2d_in_i_full_n );

    SC_METHOD(thread_dct_read_data_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_dct_read_data_U0_buf_r_pipo_status);
    sensitive << ( buf_2d_in_i_full_n );

    SC_METHOD(thread_dct_write_data_U0_ap_continue);

    SC_METHOD(thread_dct_write_data_U0_ap_start);
    sensitive << ( buf_2d_out_t_empty_n );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( dct_read_data_U0_input_r_address0 );

    SC_METHOD(thread_input_r_address1);

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( dct_read_data_U0_input_r_ce0 );

    SC_METHOD(thread_input_r_ce1);

    SC_METHOD(thread_input_r_d0);

    SC_METHOD(thread_input_r_d1);

    SC_METHOD(thread_input_r_we0);

    SC_METHOD(thread_input_r_we1);

    SC_METHOD(thread_output_r_address0);
    sensitive << ( dct_write_data_U0_output_r_address0 );

    SC_METHOD(thread_output_r_address1);

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( dct_write_data_U0_output_r_ce0 );

    SC_METHOD(thread_output_r_ce1);

    SC_METHOD(thread_output_r_d0);
    sensitive << ( dct_write_data_U0_output_r_d0 );

    SC_METHOD(thread_output_r_d1);

    SC_METHOD(thread_output_r_we0);
    sensitive << ( dct_write_data_U0_output_r_we0 );

    SC_METHOD(thread_output_r_we1);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const3);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dct_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_d0, "(port)input_r_d0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, input_r_we0, "(port)input_r_we0");
    sc_trace(mVcdFile, input_r_address1, "(port)input_r_address1");
    sc_trace(mVcdFile, input_r_ce1, "(port)input_r_ce1");
    sc_trace(mVcdFile, input_r_d1, "(port)input_r_d1");
    sc_trace(mVcdFile, input_r_q1, "(port)input_r_q1");
    sc_trace(mVcdFile, input_r_we1, "(port)input_r_we1");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, output_r_q0, "(port)output_r_q0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_address1, "(port)output_r_address1");
    sc_trace(mVcdFile, output_r_ce1, "(port)output_r_ce1");
    sc_trace(mVcdFile, output_r_d1, "(port)output_r_d1");
    sc_trace(mVcdFile, output_r_q1, "(port)output_r_q1");
    sc_trace(mVcdFile, output_r_we1, "(port)output_r_we1");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, row_outbuf_i_i_q0, "row_outbuf_i_i_q0");
    sc_trace(mVcdFile, row_outbuf_i_t_q0, "row_outbuf_i_t_q0");
    sc_trace(mVcdFile, col_outbuf_i_i_q0, "col_outbuf_i_i_q0");
    sc_trace(mVcdFile, col_outbuf_i_t_q0, "col_outbuf_i_t_q0");
    sc_trace(mVcdFile, col_inbuf_i_q0, "col_inbuf_i_q0");
    sc_trace(mVcdFile, col_inbuf_t_q0, "col_inbuf_t_q0");
    sc_trace(mVcdFile, buf_2d_in_i_q0, "buf_2d_in_i_q0");
    sc_trace(mVcdFile, buf_2d_in_t_q0, "buf_2d_in_t_q0");
    sc_trace(mVcdFile, buf_2d_out_i_q0, "buf_2d_out_i_q0");
    sc_trace(mVcdFile, buf_2d_out_t_q0, "buf_2d_out_t_q0");
    sc_trace(mVcdFile, dct_read_data_U0_ap_start, "dct_read_data_U0_ap_start");
    sc_trace(mVcdFile, dct_read_data_U0_ap_done, "dct_read_data_U0_ap_done");
    sc_trace(mVcdFile, dct_read_data_U0_ap_continue, "dct_read_data_U0_ap_continue");
    sc_trace(mVcdFile, dct_read_data_U0_ap_idle, "dct_read_data_U0_ap_idle");
    sc_trace(mVcdFile, dct_read_data_U0_ap_ready, "dct_read_data_U0_ap_ready");
    sc_trace(mVcdFile, dct_read_data_U0_input_r_address0, "dct_read_data_U0_input_r_address0");
    sc_trace(mVcdFile, dct_read_data_U0_input_r_ce0, "dct_read_data_U0_input_r_ce0");
    sc_trace(mVcdFile, dct_read_data_U0_buf_r_address0, "dct_read_data_U0_buf_r_address0");
    sc_trace(mVcdFile, dct_read_data_U0_buf_r_ce0, "dct_read_data_U0_buf_r_ce0");
    sc_trace(mVcdFile, dct_read_data_U0_buf_r_we0, "dct_read_data_U0_buf_r_we0");
    sc_trace(mVcdFile, dct_read_data_U0_buf_r_d0, "dct_read_data_U0_buf_r_d0");
    sc_trace(mVcdFile, ap_chn_write_dct_read_data_U0_buf_2d_in, "ap_chn_write_dct_read_data_U0_buf_2d_in");
    sc_trace(mVcdFile, dct_read_data_U0_buf_r_pipo_status, "dct_read_data_U0_buf_r_pipo_status");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_ap_start, "dct_Loop_Row_DCT_Loop_proc_U0_ap_start");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_ap_done, "dct_Loop_Row_DCT_Loop_proc_U0_ap_done");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_ap_continue, "dct_Loop_Row_DCT_Loop_proc_U0_ap_continue");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_ap_idle, "dct_Loop_Row_DCT_Loop_proc_U0_ap_idle");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_ap_ready, "dct_Loop_Row_DCT_Loop_proc_U0_ap_ready");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_address0, "dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_address0");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_ce0, "dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_ce0");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_address0, "dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_address0");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_ce0, "dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_ce0");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_we0, "dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_we0");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_d0, "dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_d0");
    sc_trace(mVcdFile, ap_chn_write_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i, "ap_chn_write_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i");
    sc_trace(mVcdFile, dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_pipo_status, "dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_pipo_status");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_idle, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_idle");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_ready");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_address0, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_address0");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_ce0, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_row_outbuf_i_ce0");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_address0, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_address0");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_ce0, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_ce0");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_we0, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_we0");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_d0, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_d0");
    sc_trace(mVcdFile, ap_chn_write_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf, "ap_chn_write_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf");
    sc_trace(mVcdFile, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_pipo_status, "dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_pipo_status");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_ap_start, "dct_Loop_Col_DCT_Loop_proc_U0_ap_start");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_ap_done, "dct_Loop_Col_DCT_Loop_proc_U0_ap_done");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_ap_continue, "dct_Loop_Col_DCT_Loop_proc_U0_ap_continue");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_ap_idle, "dct_Loop_Col_DCT_Loop_proc_U0_ap_idle");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_ap_ready, "dct_Loop_Col_DCT_Loop_proc_U0_ap_ready");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_address0, "dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_address0");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_ce0, "dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_ce0");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_address0, "dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_address0");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_ce0, "dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_ce0");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_we0, "dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_we0");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_d0, "dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_d0");
    sc_trace(mVcdFile, ap_chn_write_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i, "ap_chn_write_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i");
    sc_trace(mVcdFile, dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_pipo_status, "dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_pipo_status");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_idle, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_idle");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_ready");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_address0, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_address0");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_ce0, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_col_outbuf_i_ce0");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_address0, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_address0");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_ce0, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_ce0");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_we0, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_we0");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_d0, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_d0");
    sc_trace(mVcdFile, ap_chn_write_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out, "ap_chn_write_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out");
    sc_trace(mVcdFile, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_pipo_status, "dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_pipo_status");
    sc_trace(mVcdFile, dct_write_data_U0_ap_start, "dct_write_data_U0_ap_start");
    sc_trace(mVcdFile, dct_write_data_U0_ap_done, "dct_write_data_U0_ap_done");
    sc_trace(mVcdFile, dct_write_data_U0_ap_continue, "dct_write_data_U0_ap_continue");
    sc_trace(mVcdFile, dct_write_data_U0_ap_idle, "dct_write_data_U0_ap_idle");
    sc_trace(mVcdFile, dct_write_data_U0_ap_ready, "dct_write_data_U0_ap_ready");
    sc_trace(mVcdFile, dct_write_data_U0_buf_r_address0, "dct_write_data_U0_buf_r_address0");
    sc_trace(mVcdFile, dct_write_data_U0_buf_r_ce0, "dct_write_data_U0_buf_r_ce0");
    sc_trace(mVcdFile, dct_write_data_U0_output_r_address0, "dct_write_data_U0_output_r_address0");
    sc_trace(mVcdFile, dct_write_data_U0_output_r_ce0, "dct_write_data_U0_output_r_ce0");
    sc_trace(mVcdFile, dct_write_data_U0_output_r_we0, "dct_write_data_U0_output_r_we0");
    sc_trace(mVcdFile, dct_write_data_U0_output_r_d0, "dct_write_data_U0_output_r_d0");
    sc_trace(mVcdFile, ap_sig_hs_continue, "ap_sig_hs_continue");
    sc_trace(mVcdFile, buf_2d_in_i_full_n, "buf_2d_in_i_full_n");
    sc_trace(mVcdFile, buf_2d_in_t_empty_n, "buf_2d_in_t_empty_n");
    sc_trace(mVcdFile, row_outbuf_i_i_full_n, "row_outbuf_i_i_full_n");
    sc_trace(mVcdFile, row_outbuf_i_t_empty_n, "row_outbuf_i_t_empty_n");
    sc_trace(mVcdFile, col_inbuf_i_full_n, "col_inbuf_i_full_n");
    sc_trace(mVcdFile, col_inbuf_t_empty_n, "col_inbuf_t_empty_n");
    sc_trace(mVcdFile, col_outbuf_i_i_full_n, "col_outbuf_i_i_full_n");
    sc_trace(mVcdFile, col_outbuf_i_t_empty_n, "col_outbuf_i_t_empty_n");
    sc_trace(mVcdFile, buf_2d_out_i_full_n, "buf_2d_out_i_full_n");
    sc_trace(mVcdFile, buf_2d_out_t_empty_n, "buf_2d_out_t_empty_n");
    sc_trace(mVcdFile, ap_sig_hs_done, "ap_sig_hs_done");
    sc_trace(mVcdFile, ap_sig_hs_ready, "ap_sig_hs_ready");
#endif

    }
    mHdltvinHandle.open("dct.hdltvin.dat");
    mHdltvoutHandle.open("dct.hdltvout.dat");
}

dct::~dct() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete row_outbuf_i_U;
    delete col_outbuf_i_U;
    delete col_inbuf_U;
    delete buf_2d_in_U;
    delete buf_2d_out_U;
    delete dct_read_data_U0;
    delete dct_Loop_Row_DCT_Loop_proc_U0;
    delete dct_Loop_Xpose_Row_Outer_Loop_proc_U0;
    delete dct_Loop_Col_DCT_Loop_proc_U0;
    delete dct_Loop_Xpose_Col_Outer_Loop_proc_U0;
    delete dct_write_data_U0;
}

void dct::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_logic_1;
}

void dct::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_0;
}

void dct::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv16_0;
}

void dct::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv128_lc_2;
}

void dct::thread_ap_chn_write_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i() {
    ap_chn_write_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i = dct_Loop_Col_DCT_Loop_proc_U0_ap_done.read();
}

void dct::thread_ap_chn_write_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i() {
    ap_chn_write_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i = dct_Loop_Row_DCT_Loop_proc_U0_ap_done.read();
}

void dct::thread_ap_chn_write_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out() {
    ap_chn_write_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out = dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_done.read();
}

void dct::thread_ap_chn_write_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf() {
    ap_chn_write_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf = dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_done.read();
}

void dct::thread_ap_chn_write_dct_read_data_U0_buf_2d_in() {
    ap_chn_write_dct_read_data_U0_buf_2d_in = dct_read_data_U0_ap_done.read();
}

void dct::thread_ap_done() {
    ap_done = ap_sig_hs_done.read();
}

void dct::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, dct_read_data_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, dct_Loop_Row_DCT_Loop_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, dct_Loop_Col_DCT_Loop_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, dct_write_data_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, buf_2d_in_t_empty_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, row_outbuf_i_t_empty_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, col_inbuf_t_empty_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, col_outbuf_i_t_empty_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, buf_2d_out_t_empty_n.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dct::thread_ap_ready() {
    ap_ready = dct_read_data_U0_ap_ready.read();
}

void dct::thread_ap_sig_hs_continue() {
    ap_sig_hs_continue = ap_const_logic_1;
}

void dct::thread_ap_sig_hs_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, dct_write_data_U0_ap_done.read())) {
        ap_sig_hs_done = ap_const_logic_1;
    } else {
        ap_sig_hs_done = ap_const_logic_0;
    }
}

void dct::thread_ap_sig_hs_ready() {
    ap_sig_hs_ready = dct_read_data_U0_ap_ready.read();
}

void dct::thread_dct_Loop_Col_DCT_Loop_proc_U0_ap_continue() {
    dct_Loop_Col_DCT_Loop_proc_U0_ap_continue = col_outbuf_i_i_full_n.read();
}

void dct::thread_dct_Loop_Col_DCT_Loop_proc_U0_ap_start() {
    dct_Loop_Col_DCT_Loop_proc_U0_ap_start = col_inbuf_t_empty_n.read();
}

void dct::thread_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_pipo_status() {
    dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_pipo_status = col_outbuf_i_i_full_n.read();
}

void dct::thread_dct_Loop_Row_DCT_Loop_proc_U0_ap_continue() {
    dct_Loop_Row_DCT_Loop_proc_U0_ap_continue = row_outbuf_i_i_full_n.read();
}

void dct::thread_dct_Loop_Row_DCT_Loop_proc_U0_ap_start() {
    dct_Loop_Row_DCT_Loop_proc_U0_ap_start = buf_2d_in_t_empty_n.read();
}

void dct::thread_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_pipo_status() {
    dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_pipo_status = row_outbuf_i_i_full_n.read();
}

void dct::thread_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue() {
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_continue = buf_2d_out_i_full_n.read();
}

void dct::thread_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start() {
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0_ap_start = col_outbuf_i_t_empty_n.read();
}

void dct::thread_dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_pipo_status() {
    dct_Loop_Xpose_Col_Outer_Loop_proc_U0_buf_2d_out_pipo_status = buf_2d_out_i_full_n.read();
}

void dct::thread_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue() {
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_continue = col_inbuf_i_full_n.read();
}

void dct::thread_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start() {
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0_ap_start = row_outbuf_i_t_empty_n.read();
}

void dct::thread_dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_pipo_status() {
    dct_Loop_Xpose_Row_Outer_Loop_proc_U0_col_inbuf_pipo_status = col_inbuf_i_full_n.read();
}

void dct::thread_dct_read_data_U0_ap_continue() {
    dct_read_data_U0_ap_continue = buf_2d_in_i_full_n.read();
}

void dct::thread_dct_read_data_U0_ap_start() {
    dct_read_data_U0_ap_start = ap_start.read();
}

void dct::thread_dct_read_data_U0_buf_r_pipo_status() {
    dct_read_data_U0_buf_r_pipo_status = buf_2d_in_i_full_n.read();
}

void dct::thread_dct_write_data_U0_ap_continue() {
    dct_write_data_U0_ap_continue = ap_const_logic_1;
}

void dct::thread_dct_write_data_U0_ap_start() {
    dct_write_data_U0_ap_start = buf_2d_out_t_empty_n.read();
}

void dct::thread_input_r_address0() {
    input_r_address0 = dct_read_data_U0_input_r_address0.read();
}

void dct::thread_input_r_address1() {
    input_r_address1 = ap_const_lv6_0;
}

void dct::thread_input_r_ce0() {
    input_r_ce0 = dct_read_data_U0_input_r_ce0.read();
}

void dct::thread_input_r_ce1() {
    input_r_ce1 = ap_const_logic_0;
}

void dct::thread_input_r_d0() {
    input_r_d0 = ap_const_lv16_0;
}

void dct::thread_input_r_d1() {
    input_r_d1 = ap_const_lv16_0;
}

void dct::thread_input_r_we0() {
    input_r_we0 = ap_const_logic_0;
}

void dct::thread_input_r_we1() {
    input_r_we1 = ap_const_logic_0;
}

void dct::thread_output_r_address0() {
    output_r_address0 = dct_write_data_U0_output_r_address0.read();
}

void dct::thread_output_r_address1() {
    output_r_address1 = ap_const_lv6_0;
}

void dct::thread_output_r_ce0() {
    output_r_ce0 = dct_write_data_U0_output_r_ce0.read();
}

void dct::thread_output_r_ce1() {
    output_r_ce1 = ap_const_logic_0;
}

void dct::thread_output_r_d0() {
    output_r_d0 = dct_write_data_U0_output_r_d0.read();
}

void dct::thread_output_r_d1() {
    output_r_d1 = ap_const_lv16_0;
}

void dct::thread_output_r_we0() {
    output_r_we0 = dct_write_data_U0_output_r_we0.read();
}

void dct::thread_output_r_we1() {
    output_r_we1 = ap_const_logic_0;
}

void dct::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"input_r_address0\" :  \"" << input_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_ce0\" :  \"" << input_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_d0\" :  \"" << input_r_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_q0\" :  \"" << input_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_we0\" :  \"" << input_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_address1\" :  \"" << input_r_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_ce1\" :  \"" << input_r_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_d1\" :  \"" << input_r_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_q1\" :  \"" << input_r_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_we1\" :  \"" << input_r_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_address0\" :  \"" << output_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_ce0\" :  \"" << output_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_d0\" :  \"" << output_r_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_r_q0\" :  \"" << output_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_we0\" :  \"" << output_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_address1\" :  \"" << output_r_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_ce1\" :  \"" << output_r_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_d1\" :  \"" << output_r_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_r_q1\" :  \"" << output_r_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_we1\" :  \"" << output_r_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

