// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dct_read_data.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dct_read_data::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dct_read_data::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> dct_read_data::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> dct_read_data::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<4> dct_read_data::ap_ST_pp0_stg1_fsm_2 = "100";
const sc_lv<4> dct_read_data::ap_ST_st5_fsm_3 = "1000";
const sc_lv<32> dct_read_data::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dct_read_data::ap_const_lv1_1 = "1";
const sc_lv<32> dct_read_data::ap_const_lv32_1 = "1";
const sc_lv<1> dct_read_data::ap_const_lv1_0 = "0";
const sc_lv<32> dct_read_data::ap_const_lv32_2 = "10";
const sc_lv<7> dct_read_data::ap_const_lv7_0 = "0000000";
const sc_lv<4> dct_read_data::ap_const_lv4_0 = "0000";
const sc_lv<7> dct_read_data::ap_const_lv7_40 = "1000000";
const sc_lv<7> dct_read_data::ap_const_lv7_1 = "1";
const sc_lv<4> dct_read_data::ap_const_lv4_1 = "1";
const sc_lv<4> dct_read_data::ap_const_lv4_8 = "1000";
const sc_lv<3> dct_read_data::ap_const_lv3_0 = "000";
const sc_lv<7> dct_read_data::ap_const_lv7_F = "1111";
const sc_lv<8> dct_read_data::ap_const_lv8_7F = "1111111";
const sc_lv<32> dct_read_data::ap_const_lv32_7F = "1111111";
const sc_lv<128> dct_read_data::ap_const_lv128_lc_1 = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<32> dct_read_data::ap_const_lv32_3 = "11";

dct_read_data::dct_read_data(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_3 );

    SC_METHOD(thread_ap_sig_22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_271);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_86);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_99);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_56 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg1_fsm_2);
    sensitive << ( ap_sig_86 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_22 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_3);
    sensitive << ( ap_sig_271 );

    SC_METHOD(thread_buf_r_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( buf_addr_reg_353 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );

    SC_METHOD(thread_buf_r_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );

    SC_METHOD(thread_buf_r_d0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_24_fu_315_p2 );
    sensitive << ( tmp_25_fu_321_p2 );

    SC_METHOD(thread_buf_r_we0);
    sensitive << ( exitcond_flatten_reg_334 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_c_2_fu_190_p2);
    sensitive << ( c_mid2_fu_138_p3 );

    SC_METHOD(thread_c_cast2_fu_171_p1);
    sensitive << ( c_mid2_fu_138_p3 );

    SC_METHOD(thread_c_mid2_fu_138_p3);
    sensitive << ( c_phi_fu_107_p4 );
    sensitive << ( exitcond5_fu_132_p2 );

    SC_METHOD(thread_c_phi_fu_107_p4);
    sensitive << ( c_reg_103 );
    sensitive << ( exitcond_flatten_reg_334 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( c_2_reg_363 );

    SC_METHOD(thread_exitcond5_fu_132_p2);
    sensitive << ( exitcond_flatten_fu_114_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( c_phi_fu_107_p4 );

    SC_METHOD(thread_exitcond_flatten_fu_114_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( indvar_flatten_phi_fu_85_p4 );

    SC_METHOD(thread_indvar_flatten_next_fu_120_p2);
    sensitive << ( indvar_flatten_phi_fu_85_p4 );

    SC_METHOD(thread_indvar_flatten_phi_fu_85_p4);
    sensitive << ( indvar_flatten_reg_81 );
    sensitive << ( exitcond_flatten_reg_334 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( indvar_flatten_next_reg_338 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_s_fu_181_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_p_demorgan_fu_303_p2);
    sensitive << ( tmp_21_fu_291_p2 );
    sensitive << ( tmp_22_fu_297_p2 );

    SC_METHOD(thread_r_2_fu_126_p2);
    sensitive << ( r_phi_fu_96_p4 );

    SC_METHOD(thread_r_phi_fu_96_p4);
    sensitive << ( r_reg_92 );
    sensitive << ( exitcond_flatten_reg_334 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_mid2_v_v_reg_343 );

    SC_METHOD(thread_tmp_10_fu_223_p2);
    sensitive << ( tmp_6_fu_215_p1 );

    SC_METHOD(thread_tmp_11_fu_250_p3);
    sensitive << ( tmp_5_reg_373 );
    sensitive << ( tmp_6_reg_380 );
    sensitive << ( tmp_7_fu_247_p1 );

    SC_METHOD(thread_tmp_12_fu_256_p3);
    sensitive << ( tmp_5_reg_373 );
    sensitive << ( tmp_6_reg_380 );
    sensitive << ( tmp_7_fu_247_p1 );

    SC_METHOD(thread_tmp_13_fu_229_p3);
    sensitive << ( tmp_5_fu_209_p2 );
    sensitive << ( tmp_6_fu_215_p1 );
    sensitive << ( tmp_10_fu_223_p2 );

    SC_METHOD(thread_tmp_14_fu_262_p2);
    sensitive << ( tmp_11_fu_250_p3 );

    SC_METHOD(thread_tmp_15_fu_237_p1);
    sensitive << ( tmp_13_fu_229_p3 );

    SC_METHOD(thread_tmp_16_fu_268_p1);
    sensitive << ( tmp_12_fu_256_p3 );

    SC_METHOD(thread_tmp_17_fu_272_p1);
    sensitive << ( tmp_14_fu_262_p2 );

    SC_METHOD(thread_tmp_18_fu_241_p2);
    sensitive << ( tmp_8_fu_219_p1 );
    sensitive << ( tmp_15_fu_237_p1 );

    SC_METHOD(thread_tmp_19_fu_276_p4);
    sensitive << ( tmp_18_reg_386 );

    SC_METHOD(thread_tmp_20_fu_285_p3);
    sensitive << ( tmp_5_reg_373 );
    sensitive << ( tmp_18_reg_386 );
    sensitive << ( tmp_19_fu_276_p4 );

    SC_METHOD(thread_tmp_21_fu_291_p2);
    sensitive << ( tmp_16_fu_268_p1 );

    SC_METHOD(thread_tmp_22_fu_297_p2);
    sensitive << ( tmp_17_fu_272_p1 );

    SC_METHOD(thread_tmp_23_fu_309_p2);
    sensitive << ( p_demorgan_fu_303_p2 );

    SC_METHOD(thread_tmp_24_fu_315_p2);
    sensitive << ( buf_r_q0 );
    sensitive << ( tmp_23_fu_309_p2 );

    SC_METHOD(thread_tmp_25_fu_321_p2);
    sensitive << ( p_demorgan_fu_303_p2 );
    sensitive << ( tmp_20_fu_285_p3 );

    SC_METHOD(thread_tmp_2_fu_196_p3);
    sensitive << ( tmp_4_reg_358 );

    SC_METHOD(thread_tmp_3_fu_203_p2);
    sensitive << ( tmp_2_fu_196_p3 );

    SC_METHOD(thread_tmp_4_fu_186_p1);
    sensitive << ( c_mid2_fu_138_p3 );

    SC_METHOD(thread_tmp_5_fu_209_p2);
    sensitive << ( exitcond_flatten_reg_334 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_3_fu_203_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( tmp_2_fu_196_p3 );

    SC_METHOD(thread_tmp_6_fu_215_p1);
    sensitive << ( tmp_2_fu_196_p3 );

    SC_METHOD(thread_tmp_7_fu_247_p1);
    sensitive << ( tmp_3_reg_368 );

    SC_METHOD(thread_tmp_7_mid2_fu_166_p1);
    sensitive << ( tmp_mid2_v_v_fu_146_p3 );

    SC_METHOD(thread_tmp_8_fu_219_p1);
    sensitive << ( input_r_q0 );

    SC_METHOD(thread_tmp_9_fu_175_p2);
    sensitive << ( c_cast2_fu_171_p1 );
    sensitive << ( tmp_mid2_fu_158_p3 );

    SC_METHOD(thread_tmp_fu_154_p1);
    sensitive << ( tmp_mid2_v_v_fu_146_p3 );

    SC_METHOD(thread_tmp_mid2_fu_158_p3);
    sensitive << ( tmp_fu_154_p1 );

    SC_METHOD(thread_tmp_mid2_v_v_fu_146_p3);
    sensitive << ( r_phi_fu_96_p4 );
    sensitive << ( exitcond5_fu_132_p2 );
    sensitive << ( r_2_fu_126_p2 );

    SC_METHOD(thread_tmp_s_fu_181_p1);
    sensitive << ( tmp_9_fu_175_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_flatten_fu_114_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_99 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dct_read_data_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, buf_r_address0, "(port)buf_r_address0");
    sc_trace(mVcdFile, buf_r_ce0, "(port)buf_r_ce0");
    sc_trace(mVcdFile, buf_r_we0, "(port)buf_r_we0");
    sc_trace(mVcdFile, buf_r_d0, "(port)buf_r_d0");
    sc_trace(mVcdFile, buf_r_q0, "(port)buf_r_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_22, "ap_sig_22");
    sc_trace(mVcdFile, indvar_flatten_reg_81, "indvar_flatten_reg_81");
    sc_trace(mVcdFile, r_reg_92, "r_reg_92");
    sc_trace(mVcdFile, c_reg_103, "c_reg_103");
    sc_trace(mVcdFile, exitcond_flatten_fu_114_p2, "exitcond_flatten_fu_114_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_334, "exitcond_flatten_reg_334");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_56, "ap_sig_56");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, indvar_flatten_next_fu_120_p2, "indvar_flatten_next_fu_120_p2");
    sc_trace(mVcdFile, indvar_flatten_next_reg_338, "indvar_flatten_next_reg_338");
    sc_trace(mVcdFile, tmp_mid2_v_v_fu_146_p3, "tmp_mid2_v_v_fu_146_p3");
    sc_trace(mVcdFile, tmp_mid2_v_v_reg_343, "tmp_mid2_v_v_reg_343");
    sc_trace(mVcdFile, buf_addr_reg_353, "buf_addr_reg_353");
    sc_trace(mVcdFile, tmp_4_fu_186_p1, "tmp_4_fu_186_p1");
    sc_trace(mVcdFile, tmp_4_reg_358, "tmp_4_reg_358");
    sc_trace(mVcdFile, c_2_fu_190_p2, "c_2_fu_190_p2");
    sc_trace(mVcdFile, c_2_reg_363, "c_2_reg_363");
    sc_trace(mVcdFile, tmp_3_fu_203_p2, "tmp_3_fu_203_p2");
    sc_trace(mVcdFile, tmp_3_reg_368, "tmp_3_reg_368");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg1_fsm_2, "ap_sig_cseq_ST_pp0_stg1_fsm_2");
    sc_trace(mVcdFile, ap_sig_86, "ap_sig_86");
    sc_trace(mVcdFile, tmp_5_fu_209_p2, "tmp_5_fu_209_p2");
    sc_trace(mVcdFile, tmp_5_reg_373, "tmp_5_reg_373");
    sc_trace(mVcdFile, tmp_6_fu_215_p1, "tmp_6_fu_215_p1");
    sc_trace(mVcdFile, tmp_6_reg_380, "tmp_6_reg_380");
    sc_trace(mVcdFile, tmp_18_fu_241_p2, "tmp_18_fu_241_p2");
    sc_trace(mVcdFile, tmp_18_reg_386, "tmp_18_reg_386");
    sc_trace(mVcdFile, ap_sig_99, "ap_sig_99");
    sc_trace(mVcdFile, indvar_flatten_phi_fu_85_p4, "indvar_flatten_phi_fu_85_p4");
    sc_trace(mVcdFile, r_phi_fu_96_p4, "r_phi_fu_96_p4");
    sc_trace(mVcdFile, c_phi_fu_107_p4, "c_phi_fu_107_p4");
    sc_trace(mVcdFile, tmp_s_fu_181_p1, "tmp_s_fu_181_p1");
    sc_trace(mVcdFile, tmp_7_mid2_fu_166_p1, "tmp_7_mid2_fu_166_p1");
    sc_trace(mVcdFile, exitcond5_fu_132_p2, "exitcond5_fu_132_p2");
    sc_trace(mVcdFile, r_2_fu_126_p2, "r_2_fu_126_p2");
    sc_trace(mVcdFile, tmp_fu_154_p1, "tmp_fu_154_p1");
    sc_trace(mVcdFile, c_mid2_fu_138_p3, "c_mid2_fu_138_p3");
    sc_trace(mVcdFile, c_cast2_fu_171_p1, "c_cast2_fu_171_p1");
    sc_trace(mVcdFile, tmp_mid2_fu_158_p3, "tmp_mid2_fu_158_p3");
    sc_trace(mVcdFile, tmp_9_fu_175_p2, "tmp_9_fu_175_p2");
    sc_trace(mVcdFile, tmp_2_fu_196_p3, "tmp_2_fu_196_p3");
    sc_trace(mVcdFile, tmp_10_fu_223_p2, "tmp_10_fu_223_p2");
    sc_trace(mVcdFile, tmp_13_fu_229_p3, "tmp_13_fu_229_p3");
    sc_trace(mVcdFile, tmp_8_fu_219_p1, "tmp_8_fu_219_p1");
    sc_trace(mVcdFile, tmp_15_fu_237_p1, "tmp_15_fu_237_p1");
    sc_trace(mVcdFile, tmp_7_fu_247_p1, "tmp_7_fu_247_p1");
    sc_trace(mVcdFile, tmp_11_fu_250_p3, "tmp_11_fu_250_p3");
    sc_trace(mVcdFile, tmp_12_fu_256_p3, "tmp_12_fu_256_p3");
    sc_trace(mVcdFile, tmp_14_fu_262_p2, "tmp_14_fu_262_p2");
    sc_trace(mVcdFile, tmp_19_fu_276_p4, "tmp_19_fu_276_p4");
    sc_trace(mVcdFile, tmp_16_fu_268_p1, "tmp_16_fu_268_p1");
    sc_trace(mVcdFile, tmp_17_fu_272_p1, "tmp_17_fu_272_p1");
    sc_trace(mVcdFile, tmp_21_fu_291_p2, "tmp_21_fu_291_p2");
    sc_trace(mVcdFile, tmp_22_fu_297_p2, "tmp_22_fu_297_p2");
    sc_trace(mVcdFile, p_demorgan_fu_303_p2, "p_demorgan_fu_303_p2");
    sc_trace(mVcdFile, tmp_23_fu_309_p2, "tmp_23_fu_309_p2");
    sc_trace(mVcdFile, tmp_20_fu_285_p3, "tmp_20_fu_285_p3");
    sc_trace(mVcdFile, tmp_24_fu_315_p2, "tmp_24_fu_315_p2");
    sc_trace(mVcdFile, tmp_25_fu_321_p2, "tmp_25_fu_321_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_3, "ap_sig_cseq_ST_st5_fsm_3");
    sc_trace(mVcdFile, ap_sig_271, "ap_sig_271");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dct_read_data::~dct_read_data() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dct_read_data::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_3.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond_flatten_fu_114_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !ap_sig_99.read())) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
             esl_seteq<1,1,1>(exitcond_flatten_reg_334.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !ap_sig_99.read()) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
                     !esl_seteq<1,1,1>(exitcond_flatten_reg_334.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_334.read(), ap_const_lv1_0))) {
        c_reg_103 = c_2_reg_363.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_99.read())) {
        c_reg_103 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_334.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_81 = indvar_flatten_next_reg_338.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_99.read())) {
        indvar_flatten_reg_81 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_334.read(), ap_const_lv1_0))) {
        r_reg_92 = tmp_mid2_v_v_reg_343.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_99.read())) {
        r_reg_92 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_114_p2.read(), ap_const_lv1_0))) {
        buf_addr_reg_353 =  (sc_lv<3>) (tmp_7_mid2_fu_166_p1.read());
        tmp_4_reg_358 = tmp_4_fu_186_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_114_p2.read(), ap_const_lv1_0))) {
        c_2_reg_363 = c_2_fu_190_p2.read();
        tmp_mid2_v_v_reg_343 = tmp_mid2_v_v_fu_146_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
        exitcond_flatten_reg_334 = exitcond_flatten_fu_114_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        indvar_flatten_next_reg_338 = indvar_flatten_next_fu_120_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_334.read(), ap_const_lv1_0))) {
        tmp_18_reg_386 = tmp_18_fu_241_p2.read();
        tmp_3_reg_368 = tmp_3_fu_203_p2.read();
        tmp_5_reg_373 = tmp_5_fu_209_p2.read();
        tmp_6_reg_380 = tmp_6_fu_215_p1.read();
    }
}

void dct_read_data::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dct_read_data::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dct_read_data::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_3.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dct_read_data::thread_ap_sig_22() {
    ap_sig_22 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dct_read_data::thread_ap_sig_271() {
    ap_sig_271 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dct_read_data::thread_ap_sig_56() {
    ap_sig_56 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dct_read_data::thread_ap_sig_86() {
    ap_sig_86 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dct_read_data::thread_ap_sig_99() {
    ap_sig_99 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void dct_read_data::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_56.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void dct_read_data::thread_ap_sig_cseq_ST_pp0_stg1_fsm_2() {
    if (ap_sig_86.read()) {
        ap_sig_cseq_ST_pp0_stg1_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg1_fsm_2 = ap_const_logic_0;
    }
}

void dct_read_data::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_22.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dct_read_data::thread_ap_sig_cseq_ST_st5_fsm_3() {
    if (ap_sig_271.read()) {
        ap_sig_cseq_ST_st5_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_3 = ap_const_logic_0;
    }
}

void dct_read_data::thread_buf_r_address0() {
    buf_r_address0 = buf_addr_reg_353.read();
}

void dct_read_data::thread_buf_r_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read())))) {
        buf_r_ce0 = ap_const_logic_1;
    } else {
        buf_r_ce0 = ap_const_logic_0;
    }
}

void dct_read_data::thread_buf_r_d0() {
    buf_r_d0 = (tmp_24_fu_315_p2.read() | tmp_25_fu_321_p2.read());
}

void dct_read_data::thread_buf_r_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_334.read(), ap_const_lv1_0)))) {
        buf_r_we0 = ap_const_logic_1;
    } else {
        buf_r_we0 = ap_const_logic_0;
    }
}

void dct_read_data::thread_c_2_fu_190_p2() {
    c_2_fu_190_p2 = (!ap_const_lv4_1.is_01() || !c_mid2_fu_138_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(c_mid2_fu_138_p3.read()));
}

void dct_read_data::thread_c_cast2_fu_171_p1() {
    c_cast2_fu_171_p1 = esl_zext<6,4>(c_mid2_fu_138_p3.read());
}

void dct_read_data::thread_c_mid2_fu_138_p3() {
    c_mid2_fu_138_p3 = (!exitcond5_fu_132_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond5_fu_132_p2.read()[0].to_bool())? ap_const_lv4_0: c_phi_fu_107_p4.read());
}

void dct_read_data::thread_c_phi_fu_107_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_334.read(), ap_const_lv1_0))) {
        c_phi_fu_107_p4 = c_2_reg_363.read();
    } else {
        c_phi_fu_107_p4 = c_reg_103.read();
    }
}

void dct_read_data::thread_exitcond5_fu_132_p2() {
    exitcond5_fu_132_p2 = (!c_phi_fu_107_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(c_phi_fu_107_p4.read() == ap_const_lv4_8);
}

void dct_read_data::thread_exitcond_flatten_fu_114_p2() {
    exitcond_flatten_fu_114_p2 = (!indvar_flatten_phi_fu_85_p4.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_phi_fu_85_p4.read() == ap_const_lv7_40);
}

void dct_read_data::thread_indvar_flatten_next_fu_120_p2() {
    indvar_flatten_next_fu_120_p2 = (!indvar_flatten_phi_fu_85_p4.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten_phi_fu_85_p4.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void dct_read_data::thread_indvar_flatten_phi_fu_85_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_334.read(), ap_const_lv1_0))) {
        indvar_flatten_phi_fu_85_p4 = indvar_flatten_next_reg_338.read();
    } else {
        indvar_flatten_phi_fu_85_p4 = indvar_flatten_reg_81.read();
    }
}

void dct_read_data::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<6>) (tmp_s_fu_181_p1.read());
}

void dct_read_data::thread_input_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void dct_read_data::thread_p_demorgan_fu_303_p2() {
    p_demorgan_fu_303_p2 = (tmp_21_fu_291_p2.read() & tmp_22_fu_297_p2.read());
}

void dct_read_data::thread_r_2_fu_126_p2() {
    r_2_fu_126_p2 = (!ap_const_lv4_1.is_01() || !r_phi_fu_96_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(r_phi_fu_96_p4.read()));
}

void dct_read_data::thread_r_phi_fu_96_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_334.read(), ap_const_lv1_0))) {
        r_phi_fu_96_p4 = tmp_mid2_v_v_reg_343.read();
    } else {
        r_phi_fu_96_p4 = r_reg_92.read();
    }
}

void dct_read_data::thread_tmp_10_fu_223_p2() {
    tmp_10_fu_223_p2 = (tmp_6_fu_215_p1.read() ^ ap_const_lv8_7F);
}

void dct_read_data::thread_tmp_11_fu_250_p3() {
    tmp_11_fu_250_p3 = (!tmp_5_reg_373.read()[0].is_01())? sc_lv<8>(): ((tmp_5_reg_373.read()[0].to_bool())? tmp_6_reg_380.read(): tmp_7_fu_247_p1.read());
}

void dct_read_data::thread_tmp_12_fu_256_p3() {
    tmp_12_fu_256_p3 = (!tmp_5_reg_373.read()[0].is_01())? sc_lv<8>(): ((tmp_5_reg_373.read()[0].to_bool())? tmp_7_fu_247_p1.read(): tmp_6_reg_380.read());
}

void dct_read_data::thread_tmp_13_fu_229_p3() {
    tmp_13_fu_229_p3 = (!tmp_5_fu_209_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_5_fu_209_p2.read()[0].to_bool())? tmp_10_fu_223_p2.read(): tmp_6_fu_215_p1.read());
}

void dct_read_data::thread_tmp_14_fu_262_p2() {
    tmp_14_fu_262_p2 = (tmp_11_fu_250_p3.read() ^ ap_const_lv8_7F);
}

void dct_read_data::thread_tmp_15_fu_237_p1() {
    tmp_15_fu_237_p1 = esl_zext<128,8>(tmp_13_fu_229_p3.read());
}

void dct_read_data::thread_tmp_16_fu_268_p1() {
    tmp_16_fu_268_p1 = esl_zext<128,8>(tmp_12_fu_256_p3.read());
}

void dct_read_data::thread_tmp_17_fu_272_p1() {
    tmp_17_fu_272_p1 = esl_zext<128,8>(tmp_14_fu_262_p2.read());
}

void dct_read_data::thread_tmp_18_fu_241_p2() {
    tmp_18_fu_241_p2 = (!tmp_15_fu_237_p1.read().is_01())? sc_lv<128>(): tmp_8_fu_219_p1.read() << (unsigned short)tmp_15_fu_237_p1.read().to_uint();
}

void dct_read_data::thread_tmp_19_fu_276_p4() {
    tmp_19_fu_276_p4 = tmp_18_reg_386.read().range(0, 127);
}

void dct_read_data::thread_tmp_20_fu_285_p3() {
    tmp_20_fu_285_p3 = (!tmp_5_reg_373.read()[0].is_01())? sc_lv<128>(): ((tmp_5_reg_373.read()[0].to_bool())? tmp_19_fu_276_p4.read(): tmp_18_reg_386.read());
}

void dct_read_data::thread_tmp_21_fu_291_p2() {
    tmp_21_fu_291_p2 = (!tmp_16_fu_268_p1.read().is_01())? sc_lv<128>(): ap_const_lv128_lc_1 << (unsigned short)tmp_16_fu_268_p1.read().to_uint();
}

void dct_read_data::thread_tmp_22_fu_297_p2() {
    tmp_22_fu_297_p2 = (!tmp_17_fu_272_p1.read().is_01())? sc_lv<128>(): ap_const_lv128_lc_1 >> (unsigned short)tmp_17_fu_272_p1.read().to_uint();
}

void dct_read_data::thread_tmp_23_fu_309_p2() {
    tmp_23_fu_309_p2 = (p_demorgan_fu_303_p2.read() ^ ap_const_lv128_lc_1);
}

void dct_read_data::thread_tmp_24_fu_315_p2() {
    tmp_24_fu_315_p2 = (buf_r_q0.read() & tmp_23_fu_309_p2.read());
}

void dct_read_data::thread_tmp_25_fu_321_p2() {
    tmp_25_fu_321_p2 = (tmp_20_fu_285_p3.read() & p_demorgan_fu_303_p2.read());
}

void dct_read_data::thread_tmp_2_fu_196_p3() {
    tmp_2_fu_196_p3 = esl_concat<3,4>(tmp_4_reg_358.read(), ap_const_lv4_0);
}

void dct_read_data::thread_tmp_3_fu_203_p2() {
    tmp_3_fu_203_p2 = (tmp_2_fu_196_p3.read() | ap_const_lv7_F);
}

void dct_read_data::thread_tmp_4_fu_186_p1() {
    tmp_4_fu_186_p1 = c_mid2_fu_138_p3.read().range(3-1, 0);
}

void dct_read_data::thread_tmp_5_fu_209_p2() {
    tmp_5_fu_209_p2 = (!tmp_2_fu_196_p3.read().is_01() || !tmp_3_fu_203_p2.read().is_01())? sc_lv<1>(): (sc_biguint<7>(tmp_2_fu_196_p3.read()) > sc_biguint<7>(tmp_3_fu_203_p2.read()));
}

void dct_read_data::thread_tmp_6_fu_215_p1() {
    tmp_6_fu_215_p1 = esl_zext<8,7>(tmp_2_fu_196_p3.read());
}

void dct_read_data::thread_tmp_7_fu_247_p1() {
    tmp_7_fu_247_p1 = esl_zext<8,7>(tmp_3_reg_368.read());
}

void dct_read_data::thread_tmp_7_mid2_fu_166_p1() {
    tmp_7_mid2_fu_166_p1 = esl_zext<64,4>(tmp_mid2_v_v_fu_146_p3.read());
}

void dct_read_data::thread_tmp_8_fu_219_p1() {
    tmp_8_fu_219_p1 = esl_zext<128,16>(input_r_q0.read());
}

void dct_read_data::thread_tmp_9_fu_175_p2() {
    tmp_9_fu_175_p2 = (!c_cast2_fu_171_p1.read().is_01() || !tmp_mid2_fu_158_p3.read().is_01())? sc_lv<6>(): (sc_biguint<6>(c_cast2_fu_171_p1.read()) + sc_biguint<6>(tmp_mid2_fu_158_p3.read()));
}

void dct_read_data::thread_tmp_fu_154_p1() {
    tmp_fu_154_p1 = tmp_mid2_v_v_fu_146_p3.read().range(3-1, 0);
}

void dct_read_data::thread_tmp_mid2_fu_158_p3() {
    tmp_mid2_fu_158_p3 = esl_concat<3,3>(tmp_fu_154_p1.read(), ap_const_lv3_0);
}

void dct_read_data::thread_tmp_mid2_v_v_fu_146_p3() {
    tmp_mid2_v_v_fu_146_p3 = (!exitcond5_fu_132_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond5_fu_132_p2.read()[0].to_bool())? r_2_fu_126_p2.read(): r_phi_fu_96_p4.read());
}

void dct_read_data::thread_tmp_s_fu_181_p1() {
    tmp_s_fu_181_p1 = esl_zext<64,6>(tmp_9_fu_175_p2.read());
}

void dct_read_data::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_99.read()) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten_fu_114_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

