#pragma line 1 "dct.c" ::: -10
#pragma line 1 "dct.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 283 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 54
#pragma line 421 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 181
#pragma line 7 "<command line>" 2 ::: 183
#pragma line 1 "<built-in>" 2 ::: 184
#pragma line 1 "dct.c" 2 ::: 185
#pragma line 1 "./dct.h" 1 ::: 187
#pragma line 2 "dct.c" 2 ::: 202
#pragma line 1 "./dct_coeff_table.txt" 1 ::: 211
#pragma line 9 "dct.c" 2 ::: 220
#pragma line 10 "dct.c" ::: 224
