# 
# Synthesis run script generated by Vivado
# 

set_param project.defaultXPMLibraries XPM_MEMORY
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/training/hls/labs/hls_tool_flow/zc702/dct/dct_prj/solution1/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path C:/training/hls/labs/hls_tool_flow/zc702/dct/dct_prj/solution1/impl/verilog/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/training/hls/labs/hls_tool_flow/zc702/dct/dct_prj/solution1/impl/verilog/dct_dct_1d2_dct_coeff_table.v
  C:/training/hls/labs/hls_tool_flow/zc702/dct/dct_prj/solution1/impl/verilog/dct_mac_muladd_15s_16s_32ns_32_1.v
  C:/training/hls/labs/hls_tool_flow/zc702/dct/dct_prj/solution1/impl/verilog/dct_dct_1d2.v
  C:/training/hls/labs/hls_tool_flow/zc702/dct/dct_prj/solution1/impl/verilog/dct_dct_2d_row_outbuf.v
  C:/training/hls/labs/hls_tool_flow/zc702/dct/dct_prj/solution1/impl/verilog/dct_dct_2d.v
  C:/training/hls/labs/hls_tool_flow/zc702/dct/dct_prj/solution1/impl/verilog/dct.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/training/hls/labs/hls_tool_flow/zc702/dct/dct_prj/solution1/impl/verilog/dct.xdc
set_property used_in_implementation false [get_files C:/training/hls/labs/hls_tool_flow/zc702/dct/dct_prj/solution1/impl/verilog/dct.xdc]


synth_design -top dct -part xc7z020clg484-1 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef dct.dcp

catch { report_utilization -file dct_utilization_synth.rpt -pb dct_utilization_synth.pb }
