#pragma line 1 "dct.c" ::: -10
#pragma line 1 "dct.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 283 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 54
#pragma line 421 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 181
#pragma line 7 "<command line>" 2 ::: 183
#pragma line 1 "<built-in>" 2 ::: 184
#pragma line 1 "dct.c" 2 ::: 185
#pragma line 1 "./dct.h" 1 ::: 187
#pragma line 3 "dct.c" 2 ::: 202
#pragma line 1 "./dct_coeff_table.txt" 1 ::: 210
#pragma line 10 "dct.c" 2 ::: 219
#pragma line 10 "dct.c" ::: 222
#pragma line 13 "dct.c" ::: 228
#pragma line 25 "dct.c" ::: 243
#pragma line 27 "dct.c" ::: 248
#pragma line 40 "dct.c" ::: 264
#pragma line 51 "dct.c" ::: 278
#pragma line 62 "dct.c" ::: 292
#pragma line 74 "dct.c" ::: 307
#pragma line 79 "dct.c" ::: 315
#pragma line 81 "dct.c" ::: 320
