// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dct_dct_1d_HH_
#define _dct_dct_1d_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dct_mac_muladd_15s_16s_29s_29_1.h"
#include "dct_mac_muladd_14ns_16s_29s_29_1.h"
#include "dct_mul_mul_15s_16s_29_1.h"
#include "dct_mac_muladd_15s_16s_14ns_29_1.h"
#include "dct_dct_1d_dct_coeff_table_0.h"
#include "dct_dct_1d_dct_coeff_table_1.h"
#include "dct_dct_1d_dct_coeff_table_2.h"
#include "dct_dct_1d_dct_coeff_table_3.h"
#include "dct_dct_1d_dct_coeff_table_4.h"
#include "dct_dct_1d_dct_coeff_table_5.h"
#include "dct_dct_1d_dct_coeff_table_6.h"
#include "dct_dct_1d_dct_coeff_table_7.h"

namespace ap_rtl {

struct dct_dct_1d : public sc_module {
    // Port declarations 36
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<3> > src_address0;
    sc_out< sc_logic > src_ce0;
    sc_in< sc_lv<16> > src_q0;
    sc_out< sc_lv<3> > src1_address0;
    sc_out< sc_logic > src1_ce0;
    sc_in< sc_lv<16> > src1_q0;
    sc_out< sc_lv<3> > src2_address0;
    sc_out< sc_logic > src2_ce0;
    sc_in< sc_lv<16> > src2_q0;
    sc_out< sc_lv<3> > src3_address0;
    sc_out< sc_logic > src3_ce0;
    sc_in< sc_lv<16> > src3_q0;
    sc_out< sc_lv<3> > src4_address0;
    sc_out< sc_logic > src4_ce0;
    sc_in< sc_lv<16> > src4_q0;
    sc_out< sc_lv<3> > src5_address0;
    sc_out< sc_logic > src5_ce0;
    sc_in< sc_lv<16> > src5_q0;
    sc_out< sc_lv<3> > src6_address0;
    sc_out< sc_logic > src6_ce0;
    sc_in< sc_lv<16> > src6_q0;
    sc_out< sc_lv<3> > src7_address0;
    sc_out< sc_logic > src7_ce0;
    sc_in< sc_lv<16> > src7_q0;
    sc_in< sc_lv<4> > tmp_2;
    sc_out< sc_lv<6> > dst_address0;
    sc_out< sc_logic > dst_ce0;
    sc_out< sc_logic > dst_we0;
    sc_out< sc_lv<16> > dst_d0;
    sc_in< sc_lv<4> > tmp_21;


    // Module declarations
    dct_dct_1d(sc_module_name name);
    SC_HAS_PROCESS(dct_dct_1d);

    ~dct_dct_1d();

    sc_trace_file* mVcdFile;

    dct_dct_1d_dct_coeff_table_0* dct_coeff_table_0_U;
    dct_dct_1d_dct_coeff_table_1* dct_coeff_table_1_U;
    dct_dct_1d_dct_coeff_table_2* dct_coeff_table_2_U;
    dct_dct_1d_dct_coeff_table_3* dct_coeff_table_3_U;
    dct_dct_1d_dct_coeff_table_4* dct_coeff_table_4_U;
    dct_dct_1d_dct_coeff_table_5* dct_coeff_table_5_U;
    dct_dct_1d_dct_coeff_table_6* dct_coeff_table_6_U;
    dct_dct_1d_dct_coeff_table_7* dct_coeff_table_7_U;
    dct_mac_muladd_15s_16s_29s_29_1<1,1,15,16,29,29>* dct_mac_muladd_15s_16s_29s_29_1_U9;
    dct_mac_muladd_15s_16s_29s_29_1<1,1,15,16,29,29>* dct_mac_muladd_15s_16s_29s_29_1_U10;
    dct_mac_muladd_14ns_16s_29s_29_1<1,1,14,16,29,29>* dct_mac_muladd_14ns_16s_29s_29_1_U11;
    dct_mul_mul_15s_16s_29_1<1,1,15,16,29>* dct_mul_mul_15s_16s_29_1_U12;
    dct_mul_mul_15s_16s_29_1<1,1,15,16,29>* dct_mul_mul_15s_16s_29_1_U13;
    dct_mul_mul_15s_16s_29_1<1,1,15,16,29>* dct_mul_mul_15s_16s_29_1_U14;
    dct_mac_muladd_15s_16s_29s_29_1<1,1,15,16,29,29>* dct_mac_muladd_15s_16s_29s_29_1_U15;
    dct_mac_muladd_15s_16s_14ns_29_1<1,1,15,16,14,29>* dct_mac_muladd_15s_16s_14ns_29_1_U16;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_20;
    sc_signal< sc_lv<3> > dct_coeff_table_0_address0;
    sc_signal< sc_logic > dct_coeff_table_0_ce0;
    sc_signal< sc_lv<14> > dct_coeff_table_0_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_1_address0;
    sc_signal< sc_logic > dct_coeff_table_1_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_1_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_2_address0;
    sc_signal< sc_logic > dct_coeff_table_2_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_2_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_3_address0;
    sc_signal< sc_logic > dct_coeff_table_3_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_3_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_4_address0;
    sc_signal< sc_logic > dct_coeff_table_4_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_4_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_5_address0;
    sc_signal< sc_logic > dct_coeff_table_5_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_5_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_6_address0;
    sc_signal< sc_logic > dct_coeff_table_6_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_6_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_7_address0;
    sc_signal< sc_logic > dct_coeff_table_7_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_7_q0;
    sc_signal< sc_lv<4> > k_reg_290;
    sc_signal< sc_lv<8> > tmp_18_cast_fu_309_p1;
    sc_signal< sc_lv<8> > tmp_18_cast_reg_492;
    sc_signal< sc_lv<3> > src_addr_reg_497;
    sc_signal< sc_lv<3> > src1_addr_reg_502;
    sc_signal< sc_lv<3> > src2_addr_reg_507;
    sc_signal< sc_lv<3> > src3_addr_reg_512;
    sc_signal< sc_lv<3> > src4_addr_reg_517;
    sc_signal< sc_lv<3> > src5_addr_reg_522;
    sc_signal< sc_lv<3> > src6_addr_reg_527;
    sc_signal< sc_lv<3> > src7_addr_reg_532;
    sc_signal< sc_lv<1> > exitcond1_fu_325_p2;
    sc_signal< sc_lv<1> > exitcond1_reg_537;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_1;
    sc_signal< bool > ap_sig_168;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it4;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond1_reg_537_pp0_iter1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond1_reg_537_pp0_iter2;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond1_reg_537_pp0_iter3;
    sc_signal< sc_lv<4> > k_1_fu_331_p2;
    sc_signal< sc_lv<8> > tmp_8_fu_353_p2;
    sc_signal< sc_lv<8> > tmp_8_reg_546;
    sc_signal< sc_lv<8> > ap_reg_ppstg_tmp_8_reg_546_pp0_iter1;
    sc_signal< sc_lv<8> > ap_reg_ppstg_tmp_8_reg_546_pp0_iter2;
    sc_signal< sc_lv<8> > ap_reg_ppstg_tmp_8_reg_546_pp0_iter3;
    sc_signal< sc_lv<14> > dct_coeff_table_0_load_reg_591;
    sc_signal< sc_lv<14> > ap_reg_ppstg_dct_coeff_table_0_load_reg_591_pp0_iter2;
    sc_signal< sc_lv<15> > dct_coeff_table_1_load_reg_596;
    sc_signal< sc_lv<16> > src1_load_reg_601;
    sc_signal< sc_lv<15> > dct_coeff_table_2_load_reg_606;
    sc_signal< sc_lv<15> > ap_reg_ppstg_dct_coeff_table_2_load_reg_606_pp0_iter2;
    sc_signal< sc_lv<15> > dct_coeff_table_3_load_reg_611;
    sc_signal< sc_lv<16> > src3_load_reg_616;
    sc_signal< sc_lv<15> > dct_coeff_table_4_load_reg_621;
    sc_signal< sc_lv<15> > ap_reg_ppstg_dct_coeff_table_4_load_reg_621_pp0_iter2;
    sc_signal< sc_lv<15> > dct_coeff_table_5_load_reg_626;
    sc_signal< sc_lv<16> > src5_load_reg_631;
    sc_signal< sc_lv<15> > dct_coeff_table_6_load_reg_636;
    sc_signal< sc_lv<16> > src6_load_reg_641;
    sc_signal< sc_lv<15> > dct_coeff_table_7_load_reg_646;
    sc_signal< sc_lv<16> > src7_load_reg_651;
    sc_signal< sc_lv<16> > src_load_reg_656;
    sc_signal< sc_lv<29> > tmp_10_1_fu_470_p2;
    sc_signal< sc_lv<29> > tmp_10_1_reg_661;
    sc_signal< sc_lv<16> > src2_load_reg_666;
    sc_signal< sc_lv<29> > tmp_10_3_fu_464_p2;
    sc_signal< sc_lv<29> > tmp_10_3_reg_671;
    sc_signal< sc_lv<16> > src4_load_reg_676;
    sc_signal< sc_lv<29> > tmp_10_5_fu_458_p2;
    sc_signal< sc_lv<29> > tmp_10_5_reg_681;
    sc_signal< sc_lv<29> > grp_fu_476_p3;
    sc_signal< sc_lv<29> > tmp6_reg_686;
    sc_signal< sc_lv<16> > tmp_7_reg_691;
    sc_signal< sc_lv<64> > tmp_2_cast_fu_313_p1;
    sc_signal< sc_lv<64> > tmp_fu_337_p1;
    sc_signal< sc_lv<64> > tmp_19_cast_fu_430_p1;
    sc_signal< sc_lv<7> > tmp_6_fu_301_p3;
    sc_signal< sc_lv<8> > tmp_cast_fu_349_p1;
    sc_signal< sc_lv<29> > grp_fu_450_p3;
    sc_signal< sc_lv<29> > grp_fu_442_p3;
    sc_signal< sc_lv<29> > grp_fu_434_p3;
    sc_signal< sc_lv<29> > tmp1_fu_406_p2;
    sc_signal< sc_lv<29> > tmp4_fu_410_p2;
    sc_signal< sc_lv<29> > tmp_s_fu_414_p2;
    sc_signal< sc_lv<14> > grp_fu_450_p0;
    sc_signal< sc_lv<29> > grp_fu_483_p3;
    sc_signal< sc_lv<14> > grp_fu_483_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_2;
    sc_signal< bool > ap_sig_402;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_lv<29> > grp_fu_450_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_ST_pp0_stg0_fsm_1;
    static const sc_lv<3> ap_ST_st7_fsm_2;
    static const bool ap_true;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<29> ap_const_lv29_1000;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_168();
    void thread_ap_sig_20();
    void thread_ap_sig_402();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_1();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st7_fsm_2();
    void thread_dct_coeff_table_0_address0();
    void thread_dct_coeff_table_0_ce0();
    void thread_dct_coeff_table_1_address0();
    void thread_dct_coeff_table_1_ce0();
    void thread_dct_coeff_table_2_address0();
    void thread_dct_coeff_table_2_ce0();
    void thread_dct_coeff_table_3_address0();
    void thread_dct_coeff_table_3_ce0();
    void thread_dct_coeff_table_4_address0();
    void thread_dct_coeff_table_4_ce0();
    void thread_dct_coeff_table_5_address0();
    void thread_dct_coeff_table_5_ce0();
    void thread_dct_coeff_table_6_address0();
    void thread_dct_coeff_table_6_ce0();
    void thread_dct_coeff_table_7_address0();
    void thread_dct_coeff_table_7_ce0();
    void thread_dst_address0();
    void thread_dst_ce0();
    void thread_dst_d0();
    void thread_dst_we0();
    void thread_exitcond1_fu_325_p2();
    void thread_grp_fu_450_p0();
    void thread_grp_fu_450_p00();
    void thread_grp_fu_483_p2();
    void thread_k_1_fu_331_p2();
    void thread_src1_address0();
    void thread_src1_ce0();
    void thread_src2_address0();
    void thread_src2_ce0();
    void thread_src3_address0();
    void thread_src3_ce0();
    void thread_src4_address0();
    void thread_src4_ce0();
    void thread_src5_address0();
    void thread_src5_ce0();
    void thread_src6_address0();
    void thread_src6_ce0();
    void thread_src7_address0();
    void thread_src7_ce0();
    void thread_src_address0();
    void thread_src_ce0();
    void thread_tmp1_fu_406_p2();
    void thread_tmp4_fu_410_p2();
    void thread_tmp_18_cast_fu_309_p1();
    void thread_tmp_19_cast_fu_430_p1();
    void thread_tmp_2_cast_fu_313_p1();
    void thread_tmp_6_fu_301_p3();
    void thread_tmp_8_fu_353_p2();
    void thread_tmp_cast_fu_349_p1();
    void thread_tmp_fu_337_p1();
    void thread_tmp_s_fu_414_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
