// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dct_write_data_HH_
#define _dct_write_data_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct dct_write_data : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<6> > buf_r_address0;
    sc_out< sc_logic > buf_r_ce0;
    sc_in< sc_lv<16> > buf_r_q0;
    sc_out< sc_lv<6> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<16> > output_r_d0;


    // Module declarations
    dct_write_data(sc_module_name name);
    SC_HAS_PROCESS(dct_write_data);

    ~dct_write_data();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_21;
    sc_signal< sc_lv<7> > indvar_flatten_reg_73;
    sc_signal< sc_lv<4> > r_reg_84;
    sc_signal< sc_lv<4> > c_reg_95;
    sc_signal< sc_lv<1> > exitcond_flatten_fu_106_p2;
    sc_signal< sc_lv<1> > exitcond_flatten_reg_205;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_1;
    sc_signal< bool > ap_sig_54;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_lv<7> > indvar_flatten_next_fu_112_p2;
    sc_signal< sc_lv<4> > tmp_mid2_v_fu_138_p3;
    sc_signal< sc_lv<4> > tmp_mid2_v_reg_214;
    sc_signal< sc_lv<6> > tmp_4_fu_189_p2;
    sc_signal< sc_lv<6> > tmp_4_reg_224;
    sc_signal< sc_lv<4> > c_1_fu_195_p2;
    sc_signal< bool > ap_sig_78;
    sc_signal< sc_lv<4> > r_phi_fu_88_p4;
    sc_signal< sc_lv<64> > tmp_7_cast_fu_184_p1;
    sc_signal< sc_lv<64> > tmp_5_fu_201_p1;
    sc_signal< sc_lv<1> > exitcond2_fu_124_p2;
    sc_signal< sc_lv<4> > r_1_fu_118_p2;
    sc_signal< sc_lv<7> > tmp_fu_146_p3;
    sc_signal< sc_lv<3> > tmp_1_fu_158_p1;
    sc_signal< sc_lv<4> > c_mid2_fu_130_p3;
    sc_signal< sc_lv<8> > tmp_1_cast_fu_154_p1;
    sc_signal< sc_lv<8> > tmp_3_cast_fu_174_p1;
    sc_signal< sc_lv<8> > tmp_7_fu_178_p2;
    sc_signal< sc_lv<6> > c_cast6_fu_170_p1;
    sc_signal< sc_lv<6> > tmp_1_mid2_fu_162_p3;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_2;
    sc_signal< bool > ap_sig_163;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_ST_pp0_stg0_fsm_1;
    static const sc_lv<3> ap_ST_st4_fsm_2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<7> ap_const_lv7_40;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_163();
    void thread_ap_sig_21();
    void thread_ap_sig_54();
    void thread_ap_sig_78();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_1();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st4_fsm_2();
    void thread_buf_r_address0();
    void thread_buf_r_ce0();
    void thread_c_1_fu_195_p2();
    void thread_c_cast6_fu_170_p1();
    void thread_c_mid2_fu_130_p3();
    void thread_exitcond2_fu_124_p2();
    void thread_exitcond_flatten_fu_106_p2();
    void thread_indvar_flatten_next_fu_112_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_r_1_fu_118_p2();
    void thread_r_phi_fu_88_p4();
    void thread_tmp_1_cast_fu_154_p1();
    void thread_tmp_1_fu_158_p1();
    void thread_tmp_1_mid2_fu_162_p3();
    void thread_tmp_3_cast_fu_174_p1();
    void thread_tmp_4_fu_189_p2();
    void thread_tmp_5_fu_201_p1();
    void thread_tmp_7_cast_fu_184_p1();
    void thread_tmp_7_fu_178_p2();
    void thread_tmp_fu_146_p3();
    void thread_tmp_mid2_v_fu_138_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
