// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "yuv_filter_rgb2yuv.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic yuv_filter_rgb2yuv::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic yuv_filter_rgb2yuv::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> yuv_filter_rgb2yuv::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> yuv_filter_rgb2yuv::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<3> yuv_filter_rgb2yuv::ap_ST_st11_fsm_2 = "100";
const bool yuv_filter_rgb2yuv::ap_true = true;
const sc_lv<32> yuv_filter_rgb2yuv::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> yuv_filter_rgb2yuv::ap_const_lv1_1 = "1";
const sc_lv<32> yuv_filter_rgb2yuv::ap_const_lv32_1 = "1";
const sc_lv<1> yuv_filter_rgb2yuv::ap_const_lv1_0 = "0";
const sc_lv<16> yuv_filter_rgb2yuv::ap_const_lv16_0 = "0000000000000000";
const sc_lv<16> yuv_filter_rgb2yuv::ap_const_lv16_1 = "1";
const sc_lv<10> yuv_filter_rgb2yuv::ap_const_lv10_0 = "0000000000";
const sc_lv<8> yuv_filter_rgb2yuv::ap_const_lv8_0 = "00000000";
const sc_lv<16> yuv_filter_rgb2yuv::ap_const_lv16_FFB6 = "1111111110110110";
const sc_lv<16> yuv_filter_rgb2yuv::ap_const_lv16_7A = "1111010";
const sc_lv<6> yuv_filter_rgb2yuv::ap_const_lv6_0 = "000000";
const sc_lv<7> yuv_filter_rgb2yuv::ap_const_lv7_0 = "0000000";
const sc_lv<9> yuv_filter_rgb2yuv::ap_const_lv9_80 = "10000000";
const sc_lv<32> yuv_filter_rgb2yuv::ap_const_lv32_8 = "1000";
const sc_lv<32> yuv_filter_rgb2yuv::ap_const_lv32_F = "1111";
const sc_lv<4> yuv_filter_rgb2yuv::ap_const_lv4_0 = "0000";
const sc_lv<16> yuv_filter_rgb2yuv::ap_const_lv16_80 = "10000000";
const sc_lv<13> yuv_filter_rgb2yuv::ap_const_lv13_0 = "0000000000000";
const sc_lv<14> yuv_filter_rgb2yuv::ap_const_lv14_80 = "10000000";
const sc_lv<8> yuv_filter_rgb2yuv::ap_const_lv8_10 = "10000";
const sc_lv<8> yuv_filter_rgb2yuv::ap_const_lv8_80 = "10000000";
const sc_lv<32> yuv_filter_rgb2yuv::ap_const_lv32_2 = "10";
const sc_lv<16> yuv_filter_rgb2yuv::ap_const_lv16_FFA2 = "1111111110100010";
const sc_lv<15> yuv_filter_rgb2yuv::ap_const_lv15_7FDA = "111111111011010";
const sc_lv<13> yuv_filter_rgb2yuv::ap_const_lv13_19 = "11001";

yuv_filter_rgb2yuv::yuv_filter_rgb2yuv(sc_module_name name) : sc_module(name), mVcdFile(0) {
    yuv_filter_mul_mul_16ns_16ns_32_1_U0 = new yuv_filter_mul_mul_16ns_16ns_32_1<1,1,16,16,32>("yuv_filter_mul_mul_16ns_16ns_32_1_U0");
    yuv_filter_mul_mul_16ns_16ns_32_1_U0->din0(bound_fu_558_p0);
    yuv_filter_mul_mul_16ns_16ns_32_1_U0->din1(bound_fu_558_p1);
    yuv_filter_mul_mul_16ns_16ns_32_1_U0->dout(bound_fu_558_p2);
    yuv_filter_mac_muladd_8s_8ns_16ns_16_1_U1 = new yuv_filter_mac_muladd_8s_8ns_16ns_16_1<1,1,8,8,16,16>("yuv_filter_mac_muladd_8s_8ns_16ns_16_1_U1");
    yuv_filter_mac_muladd_8s_8ns_16ns_16_1_U1->din0(grp_fu_564_p0);
    yuv_filter_mac_muladd_8s_8ns_16ns_16_1_U1->din1(grp_fu_564_p1);
    yuv_filter_mac_muladd_8s_8ns_16ns_16_1_U1->din2(tmp_31_reg_684);
    yuv_filter_mac_muladd_8s_8ns_16ns_16_1_U1->dout(grp_fu_564_p3);
    yuv_filter_mac_muladd_7s_8ns_16ns_16_1_U2 = new yuv_filter_mac_muladd_7s_8ns_16ns_16_1<1,1,7,8,16,16>("yuv_filter_mac_muladd_7s_8ns_16ns_16_1_U2");
    yuv_filter_mac_muladd_7s_8ns_16ns_16_1_U2->din0(grp_fu_571_p0);
    yuv_filter_mac_muladd_7s_8ns_16ns_16_1_U2->din1(grp_fu_571_p1);
    yuv_filter_mac_muladd_7s_8ns_16ns_16_1_U2->din2(tmp_27_reg_679);
    yuv_filter_mac_muladd_7s_8ns_16ns_16_1_U2->dout(grp_fu_571_p3);
    yuv_filter_mac_muladd_6ns_8ns_9ns_13_1_U3 = new yuv_filter_mac_muladd_6ns_8ns_9ns_13_1<1,1,6,8,9,13>("yuv_filter_mac_muladd_6ns_8ns_9ns_13_1_U3");
    yuv_filter_mac_muladd_6ns_8ns_9ns_13_1_U3->din0(grp_fu_579_p0);
    yuv_filter_mac_muladd_6ns_8ns_9ns_13_1_U3->din1(grp_fu_579_p1);
    yuv_filter_mac_muladd_6ns_8ns_9ns_13_1_U3->din2(grp_fu_579_p2);
    yuv_filter_mac_muladd_6ns_8ns_9ns_13_1_U3->dout(grp_fu_579_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( out_width );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( out_height );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_2 );

    SC_METHOD(thread_ap_sig_20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_379);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_91);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_91 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_2);
    sensitive << ( ap_sig_379 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_20 );

    SC_METHOD(thread_bound_fu_558_p0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( bound_fu_558_p00 );

    SC_METHOD(thread_bound_fu_558_p00);
    sensitive << ( out_height );

    SC_METHOD(thread_bound_fu_558_p1);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( bound_fu_558_p10 );

    SC_METHOD(thread_bound_fu_558_p10);
    sensitive << ( out_width );

    SC_METHOD(thread_exitcond9_fu_248_p2);
    sensitive << ( out_height );
    sensitive << ( y_reg_212 );
    sensitive << ( exitcond_flatten_fu_231_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_flatten_fu_231_p2);
    sensitive << ( indvar_flatten_reg_190 );
    sensitive << ( bound_reg_599 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_grp_fu_564_p0);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5 );

    SC_METHOD(thread_grp_fu_564_p1);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5 );
    sensitive << ( tmp_35_cast1_reg_674 );

    SC_METHOD(thread_grp_fu_571_p0);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5 );

    SC_METHOD(thread_grp_fu_571_p1);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5 );
    sensitive << ( grp_fu_571_p10 );

    SC_METHOD(thread_grp_fu_571_p10);
    sensitive << ( ap_reg_ppstg_R_reg_651_pp0_iter5 );

    SC_METHOD(thread_grp_fu_579_p0);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5 );

    SC_METHOD(thread_grp_fu_579_p1);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5 );
    sensitive << ( grp_fu_579_p10 );

    SC_METHOD(thread_grp_fu_579_p10);
    sensitive << ( B_reg_666 );

    SC_METHOD(thread_grp_fu_579_p2);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5 );
    sensitive << ( grp_fu_579_p20 );

    SC_METHOD(thread_grp_fu_579_p20);
    sensitive << ( tmp4_fu_396_p2 );

    SC_METHOD(thread_in_channels_ch1_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_24_cast_fu_315_p1 );

    SC_METHOD(thread_in_channels_ch1_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_in_channels_ch2_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_24_cast_fu_315_p1 );

    SC_METHOD(thread_in_channels_ch2_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_in_channels_ch3_address0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( tmp_24_cast_reg_628 );

    SC_METHOD(thread_in_channels_ch3_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_indvar_flatten_next_fu_236_p2);
    sensitive << ( indvar_flatten_reg_190 );

    SC_METHOD(thread_out_channels_ch1_address0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter6 );

    SC_METHOD(thread_out_channels_ch1_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );

    SC_METHOD(thread_out_channels_ch1_d0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( tmp_25_reg_689 );

    SC_METHOD(thread_out_channels_ch1_we0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter6 );

    SC_METHOD(thread_out_channels_ch2_address0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter6 );

    SC_METHOD(thread_out_channels_ch2_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );

    SC_METHOD(thread_out_channels_ch2_d0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( tmp_30_reg_694 );

    SC_METHOD(thread_out_channels_ch2_we0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter6 );

    SC_METHOD(thread_out_channels_ch3_address0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter6 );

    SC_METHOD(thread_out_channels_ch3_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );

    SC_METHOD(thread_out_channels_ch3_d0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( tmp_35_reg_699 );

    SC_METHOD(thread_out_channels_ch3_we0);
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter6 );

    SC_METHOD(thread_p_neg_cast_fu_484_p1);
    sensitive << ( p_neg_fu_478_p2 );

    SC_METHOD(thread_p_neg_fu_478_p2);
    sensitive << ( p_shl3_cast9_fu_443_p1 );

    SC_METHOD(thread_p_shl1_cast_fu_495_p1);
    sensitive << ( p_shl1_fu_488_p3 );

    SC_METHOD(thread_p_shl1_fu_488_p3);
    sensitive << ( B_reg_666 );

    SC_METHOD(thread_p_shl2_cast_fu_432_p1);
    sensitive << ( p_shl2_fu_425_p3 );

    SC_METHOD(thread_p_shl2_fu_425_p3);
    sensitive << ( B_reg_666 );

    SC_METHOD(thread_p_shl3_cast9_fu_443_p1);
    sensitive << ( p_shl3_fu_436_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_447_p1);
    sensitive << ( p_shl3_fu_436_p3 );

    SC_METHOD(thread_p_shl3_fu_436_p3);
    sensitive << ( B_reg_666 );

    SC_METHOD(thread_p_shl4_cast_fu_373_p1);
    sensitive << ( p_shl4_fu_366_p3 );

    SC_METHOD(thread_p_shl4_fu_366_p3);
    sensitive << ( ap_reg_ppstg_G_reg_659_pp0_iter5 );

    SC_METHOD(thread_p_shl5_cast_fu_348_p1);
    sensitive << ( p_shl5_fu_341_p3 );

    SC_METHOD(thread_p_shl5_fu_341_p3);
    sensitive << ( ap_reg_ppstg_R_reg_651_pp0_iter5 );

    SC_METHOD(thread_p_shl6_cast_fu_359_p1);
    sensitive << ( p_shl6_fu_352_p3 );

    SC_METHOD(thread_p_shl6_fu_352_p3);
    sensitive << ( ap_reg_ppstg_R_reg_651_pp0_iter5 );

    SC_METHOD(thread_p_shl7_cast_fu_285_p3);
    sensitive << ( tmp_20_fu_281_p1 );

    SC_METHOD(thread_p_shl_cast_fu_273_p3);
    sensitive << ( tmp_fu_269_p1 );

    SC_METHOD(thread_tmp1_fu_390_p2);
    sensitive << ( tmp2_cast_fu_386_p1 );
    sensitive << ( p_shl4_cast_fu_373_p1 );

    SC_METHOD(thread_tmp2_cast_fu_386_p1);
    sensitive << ( tmp2_fu_380_p2 );

    SC_METHOD(thread_tmp2_fu_380_p2);
    sensitive << ( p_shl6_cast_fu_359_p1 );
    sensitive << ( p_shl5_cast_fu_348_p1 );

    SC_METHOD(thread_tmp3_cast_fu_406_p1);
    sensitive << ( grp_fu_579_p3 );

    SC_METHOD(thread_tmp4_fu_396_p2);
    sensitive << ( tmp_35_cast2_fu_363_p1 );

    SC_METHOD(thread_tmp6_fu_457_p2);
    sensitive << ( tmp_28_fu_451_p2 );

    SC_METHOD(thread_tmp8_cast_fu_511_p1);
    sensitive << ( tmp8_fu_505_p2 );

    SC_METHOD(thread_tmp8_fu_505_p2);
    sensitive << ( tmp_33_fu_499_p2 );

    SC_METHOD(thread_tmp_20_fu_281_p1);
    sensitive << ( tmp_mid2_v_fu_261_p3 );

    SC_METHOD(thread_tmp_22_fu_303_p2);
    sensitive << ( tmp_cast_fu_299_p1 );
    sensitive << ( tmp_s_fu_293_p2 );

    SC_METHOD(thread_tmp_24_cast_fu_315_p1);
    sensitive << ( tmp_22_reg_618 );

    SC_METHOD(thread_tmp_24_fu_409_p2);
    sensitive << ( tmp3_cast_fu_406_p1 );
    sensitive << ( tmp1_fu_390_p2 );

    SC_METHOD(thread_tmp_27_fu_326_p1);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( tmp_27_fu_326_p10 );

    SC_METHOD(thread_tmp_27_fu_326_p10);
    sensitive << ( G_reg_659 );

    SC_METHOD(thread_tmp_27_fu_326_p2);
    sensitive << ( tmp_27_fu_326_p1 );

    SC_METHOD(thread_tmp_28_fu_451_p2);
    sensitive << ( p_shl2_cast_fu_432_p1 );
    sensitive << ( p_shl3_cast_fu_447_p1 );

    SC_METHOD(thread_tmp_29_fu_463_p2);
    sensitive << ( tmp6_fu_457_p2 );
    sensitive << ( grp_fu_571_p3 );

    SC_METHOD(thread_tmp_31_fu_332_p1);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( tmp_31_fu_332_p10 );

    SC_METHOD(thread_tmp_31_fu_332_p10);
    sensitive << ( R_reg_651 );

    SC_METHOD(thread_tmp_31_fu_332_p2);
    sensitive << ( tmp_31_fu_332_p1 );

    SC_METHOD(thread_tmp_33_fu_499_p2);
    sensitive << ( p_neg_cast_fu_484_p1 );
    sensitive << ( p_shl1_cast_fu_495_p1 );

    SC_METHOD(thread_tmp_34_fu_515_p2);
    sensitive << ( tmp8_cast_fu_511_p1 );
    sensitive << ( grp_fu_564_p3 );

    SC_METHOD(thread_tmp_35_cast1_fu_323_p1);
    sensitive << ( G_reg_659 );

    SC_METHOD(thread_tmp_35_cast2_fu_363_p1);
    sensitive << ( ap_reg_ppstg_G_reg_659_pp0_iter5 );

    SC_METHOD(thread_tmp_cast_fu_299_p1);
    sensitive << ( y_mid2_fu_253_p3 );

    SC_METHOD(thread_tmp_fu_269_p1);
    sensitive << ( tmp_mid2_v_fu_261_p3 );

    SC_METHOD(thread_tmp_mid2_v_fu_261_p3);
    sensitive << ( x_phi_fu_205_p4 );
    sensitive << ( exitcond9_fu_248_p2 );
    sensitive << ( x_2_fu_242_p2 );

    SC_METHOD(thread_tmp_s_fu_293_p2);
    sensitive << ( p_shl_cast_fu_273_p3 );
    sensitive << ( p_shl7_cast_fu_285_p3 );

    SC_METHOD(thread_x_2_fu_242_p2);
    sensitive << ( x_phi_fu_205_p4 );

    SC_METHOD(thread_x_phi_fu_205_p4);
    sensitive << ( x_reg_201 );
    sensitive << ( exitcond_flatten_reg_604 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_mid2_v_reg_613 );

    SC_METHOD(thread_y_2_fu_309_p2);
    sensitive << ( y_mid2_fu_253_p3 );

    SC_METHOD(thread_y_mid2_fu_253_p3);
    sensitive << ( y_reg_212 );
    sensitive << ( exitcond9_fu_248_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_flatten_fu_231_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );

    ap_CS_fsm = "001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it6 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it7 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it8 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "yuv_filter_rgb2yuv_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_channels_ch1_address0, "(port)in_channels_ch1_address0");
    sc_trace(mVcdFile, in_channels_ch1_ce0, "(port)in_channels_ch1_ce0");
    sc_trace(mVcdFile, in_channels_ch1_q0, "(port)in_channels_ch1_q0");
    sc_trace(mVcdFile, in_channels_ch2_address0, "(port)in_channels_ch2_address0");
    sc_trace(mVcdFile, in_channels_ch2_ce0, "(port)in_channels_ch2_ce0");
    sc_trace(mVcdFile, in_channels_ch2_q0, "(port)in_channels_ch2_q0");
    sc_trace(mVcdFile, in_channels_ch3_address0, "(port)in_channels_ch3_address0");
    sc_trace(mVcdFile, in_channels_ch3_ce0, "(port)in_channels_ch3_ce0");
    sc_trace(mVcdFile, in_channels_ch3_q0, "(port)in_channels_ch3_q0");
    sc_trace(mVcdFile, out_width, "(port)out_width");
    sc_trace(mVcdFile, out_height, "(port)out_height");
    sc_trace(mVcdFile, out_channels_ch1_address0, "(port)out_channels_ch1_address0");
    sc_trace(mVcdFile, out_channels_ch1_ce0, "(port)out_channels_ch1_ce0");
    sc_trace(mVcdFile, out_channels_ch1_we0, "(port)out_channels_ch1_we0");
    sc_trace(mVcdFile, out_channels_ch1_d0, "(port)out_channels_ch1_d0");
    sc_trace(mVcdFile, out_channels_ch2_address0, "(port)out_channels_ch2_address0");
    sc_trace(mVcdFile, out_channels_ch2_ce0, "(port)out_channels_ch2_ce0");
    sc_trace(mVcdFile, out_channels_ch2_we0, "(port)out_channels_ch2_we0");
    sc_trace(mVcdFile, out_channels_ch2_d0, "(port)out_channels_ch2_d0");
    sc_trace(mVcdFile, out_channels_ch3_address0, "(port)out_channels_ch3_address0");
    sc_trace(mVcdFile, out_channels_ch3_ce0, "(port)out_channels_ch3_ce0");
    sc_trace(mVcdFile, out_channels_ch3_we0, "(port)out_channels_ch3_we0");
    sc_trace(mVcdFile, out_channels_ch3_d0, "(port)out_channels_ch3_d0");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_20, "ap_sig_20");
    sc_trace(mVcdFile, indvar_flatten_reg_190, "indvar_flatten_reg_190");
    sc_trace(mVcdFile, x_reg_201, "x_reg_201");
    sc_trace(mVcdFile, y_reg_212, "y_reg_212");
    sc_trace(mVcdFile, bound_fu_558_p2, "bound_fu_558_p2");
    sc_trace(mVcdFile, bound_reg_599, "bound_reg_599");
    sc_trace(mVcdFile, exitcond_flatten_fu_231_p2, "exitcond_flatten_fu_231_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_604, "exitcond_flatten_reg_604");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_91, "ap_sig_91");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it6, "ap_reg_ppiten_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it7, "ap_reg_ppiten_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it8, "ap_reg_ppiten_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter1, "ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter2, "ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter3, "ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter4, "ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5, "ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter6, "ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter6");
    sc_trace(mVcdFile, indvar_flatten_next_fu_236_p2, "indvar_flatten_next_fu_236_p2");
    sc_trace(mVcdFile, tmp_mid2_v_fu_261_p3, "tmp_mid2_v_fu_261_p3");
    sc_trace(mVcdFile, tmp_mid2_v_reg_613, "tmp_mid2_v_reg_613");
    sc_trace(mVcdFile, tmp_22_fu_303_p2, "tmp_22_fu_303_p2");
    sc_trace(mVcdFile, tmp_22_reg_618, "tmp_22_reg_618");
    sc_trace(mVcdFile, y_2_fu_309_p2, "y_2_fu_309_p2");
    sc_trace(mVcdFile, tmp_24_cast_fu_315_p1, "tmp_24_cast_fu_315_p1");
    sc_trace(mVcdFile, tmp_24_cast_reg_628, "tmp_24_cast_reg_628");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter2, "ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter3, "ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter4, "ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter5, "ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter6, "ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter6");
    sc_trace(mVcdFile, R_reg_651, "R_reg_651");
    sc_trace(mVcdFile, ap_reg_ppstg_R_reg_651_pp0_iter5, "ap_reg_ppstg_R_reg_651_pp0_iter5");
    sc_trace(mVcdFile, G_reg_659, "G_reg_659");
    sc_trace(mVcdFile, ap_reg_ppstg_G_reg_659_pp0_iter5, "ap_reg_ppstg_G_reg_659_pp0_iter5");
    sc_trace(mVcdFile, B_reg_666, "B_reg_666");
    sc_trace(mVcdFile, tmp_35_cast1_fu_323_p1, "tmp_35_cast1_fu_323_p1");
    sc_trace(mVcdFile, tmp_35_cast1_reg_674, "tmp_35_cast1_reg_674");
    sc_trace(mVcdFile, tmp_27_fu_326_p2, "tmp_27_fu_326_p2");
    sc_trace(mVcdFile, tmp_27_reg_679, "tmp_27_reg_679");
    sc_trace(mVcdFile, tmp_31_fu_332_p2, "tmp_31_fu_332_p2");
    sc_trace(mVcdFile, tmp_31_reg_684, "tmp_31_reg_684");
    sc_trace(mVcdFile, tmp_25_reg_689, "tmp_25_reg_689");
    sc_trace(mVcdFile, tmp_30_reg_694, "tmp_30_reg_694");
    sc_trace(mVcdFile, tmp_35_reg_699, "tmp_35_reg_699");
    sc_trace(mVcdFile, x_phi_fu_205_p4, "x_phi_fu_205_p4");
    sc_trace(mVcdFile, exitcond9_fu_248_p2, "exitcond9_fu_248_p2");
    sc_trace(mVcdFile, x_2_fu_242_p2, "x_2_fu_242_p2");
    sc_trace(mVcdFile, tmp_fu_269_p1, "tmp_fu_269_p1");
    sc_trace(mVcdFile, tmp_20_fu_281_p1, "tmp_20_fu_281_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_273_p3, "p_shl_cast_fu_273_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_285_p3, "p_shl7_cast_fu_285_p3");
    sc_trace(mVcdFile, y_mid2_fu_253_p3, "y_mid2_fu_253_p3");
    sc_trace(mVcdFile, tmp_cast_fu_299_p1, "tmp_cast_fu_299_p1");
    sc_trace(mVcdFile, tmp_s_fu_293_p2, "tmp_s_fu_293_p2");
    sc_trace(mVcdFile, tmp_27_fu_326_p1, "tmp_27_fu_326_p1");
    sc_trace(mVcdFile, tmp_31_fu_332_p1, "tmp_31_fu_332_p1");
    sc_trace(mVcdFile, p_shl5_fu_341_p3, "p_shl5_fu_341_p3");
    sc_trace(mVcdFile, p_shl6_fu_352_p3, "p_shl6_fu_352_p3");
    sc_trace(mVcdFile, p_shl4_fu_366_p3, "p_shl4_fu_366_p3");
    sc_trace(mVcdFile, p_shl6_cast_fu_359_p1, "p_shl6_cast_fu_359_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_348_p1, "p_shl5_cast_fu_348_p1");
    sc_trace(mVcdFile, tmp2_fu_380_p2, "tmp2_fu_380_p2");
    sc_trace(mVcdFile, tmp2_cast_fu_386_p1, "tmp2_cast_fu_386_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_373_p1, "p_shl4_cast_fu_373_p1");
    sc_trace(mVcdFile, tmp_35_cast2_fu_363_p1, "tmp_35_cast2_fu_363_p1");
    sc_trace(mVcdFile, tmp4_fu_396_p2, "tmp4_fu_396_p2");
    sc_trace(mVcdFile, grp_fu_579_p3, "grp_fu_579_p3");
    sc_trace(mVcdFile, tmp3_cast_fu_406_p1, "tmp3_cast_fu_406_p1");
    sc_trace(mVcdFile, tmp1_fu_390_p2, "tmp1_fu_390_p2");
    sc_trace(mVcdFile, tmp_24_fu_409_p2, "tmp_24_fu_409_p2");
    sc_trace(mVcdFile, p_shl2_fu_425_p3, "p_shl2_fu_425_p3");
    sc_trace(mVcdFile, p_shl3_fu_436_p3, "p_shl3_fu_436_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_432_p1, "p_shl2_cast_fu_432_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_447_p1, "p_shl3_cast_fu_447_p1");
    sc_trace(mVcdFile, tmp_28_fu_451_p2, "tmp_28_fu_451_p2");
    sc_trace(mVcdFile, tmp6_fu_457_p2, "tmp6_fu_457_p2");
    sc_trace(mVcdFile, grp_fu_571_p3, "grp_fu_571_p3");
    sc_trace(mVcdFile, tmp_29_fu_463_p2, "tmp_29_fu_463_p2");
    sc_trace(mVcdFile, p_shl3_cast9_fu_443_p1, "p_shl3_cast9_fu_443_p1");
    sc_trace(mVcdFile, p_neg_fu_478_p2, "p_neg_fu_478_p2");
    sc_trace(mVcdFile, p_shl1_fu_488_p3, "p_shl1_fu_488_p3");
    sc_trace(mVcdFile, p_neg_cast_fu_484_p1, "p_neg_cast_fu_484_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_495_p1, "p_shl1_cast_fu_495_p1");
    sc_trace(mVcdFile, tmp_33_fu_499_p2, "tmp_33_fu_499_p2");
    sc_trace(mVcdFile, tmp8_fu_505_p2, "tmp8_fu_505_p2");
    sc_trace(mVcdFile, tmp8_cast_fu_511_p1, "tmp8_cast_fu_511_p1");
    sc_trace(mVcdFile, grp_fu_564_p3, "grp_fu_564_p3");
    sc_trace(mVcdFile, tmp_34_fu_515_p2, "tmp_34_fu_515_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_2, "ap_sig_cseq_ST_st11_fsm_2");
    sc_trace(mVcdFile, ap_sig_379, "ap_sig_379");
    sc_trace(mVcdFile, bound_fu_558_p0, "bound_fu_558_p0");
    sc_trace(mVcdFile, bound_fu_558_p1, "bound_fu_558_p1");
    sc_trace(mVcdFile, grp_fu_564_p0, "grp_fu_564_p0");
    sc_trace(mVcdFile, grp_fu_564_p1, "grp_fu_564_p1");
    sc_trace(mVcdFile, grp_fu_571_p0, "grp_fu_571_p0");
    sc_trace(mVcdFile, grp_fu_571_p1, "grp_fu_571_p1");
    sc_trace(mVcdFile, grp_fu_579_p0, "grp_fu_579_p0");
    sc_trace(mVcdFile, grp_fu_579_p1, "grp_fu_579_p1");
    sc_trace(mVcdFile, grp_fu_579_p2, "grp_fu_579_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, bound_fu_558_p00, "bound_fu_558_p00");
    sc_trace(mVcdFile, bound_fu_558_p10, "bound_fu_558_p10");
    sc_trace(mVcdFile, grp_fu_571_p10, "grp_fu_571_p10");
    sc_trace(mVcdFile, grp_fu_579_p10, "grp_fu_579_p10");
    sc_trace(mVcdFile, grp_fu_579_p20, "grp_fu_579_p20");
    sc_trace(mVcdFile, tmp_27_fu_326_p10, "tmp_27_fu_326_p10");
    sc_trace(mVcdFile, tmp_31_fu_332_p10, "tmp_31_fu_332_p10");
#endif

    }
}

yuv_filter_rgb2yuv::~yuv_filter_rgb2yuv() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete yuv_filter_mul_mul_16ns_16ns_32_1_U0;
    delete yuv_filter_mac_muladd_8s_8ns_16ns_16_1_U1;
    delete yuv_filter_mac_muladd_7s_8ns_16ns_16_1_U2;
    delete yuv_filter_mac_muladd_6ns_8ns_9ns_13_1_U3;
}

void yuv_filter_rgb2yuv::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond_flatten_fu_231_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             esl_seteq<1,1,1>(exitcond_flatten_fu_231_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                     !esl_seteq<1,1,1>(exitcond_flatten_fu_231_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it6 = ap_reg_ppiten_pp0_it5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it7 = ap_reg_ppiten_pp0_it6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it8 = ap_reg_ppiten_pp0_it7.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_231_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_190 = indvar_flatten_next_fu_236_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten_reg_190 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_604.read(), ap_const_lv1_0))) {
        x_reg_201 = tmp_mid2_v_reg_613.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        x_reg_201 = ap_const_lv16_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_231_p2.read(), ap_const_lv1_0))) {
        y_reg_212 = y_2_fu_309_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        y_reg_212 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter4.read(), ap_const_lv1_0)) {
        B_reg_666 = in_channels_ch3_q0.read();
        tmp_27_reg_679 = tmp_27_fu_326_p2.read();
        tmp_31_reg_684 = tmp_31_fu_332_p2.read();
        tmp_35_cast1_reg_674 = tmp_35_cast1_fu_323_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter3.read(), ap_const_lv1_0)) {
        G_reg_659 = in_channels_ch2_q0.read();
        R_reg_651 = in_channels_ch1_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_true, ap_true)) {
        ap_reg_ppstg_G_reg_659_pp0_iter5 = G_reg_659.read();
        ap_reg_ppstg_R_reg_651_pp0_iter5 = R_reg_651.read();
        ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter2 = ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter1.read();
        ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter3 = ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter2.read();
        ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter4 = ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter3.read();
        ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5 = ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter4.read();
        ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter6 = ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5.read();
        ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter2 = tmp_24_cast_reg_628.read();
        ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter3 = ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter2.read();
        ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter4 = ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter3.read();
        ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter5 = ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter4.read();
        ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter6 = ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter5.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
        ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter1 = exitcond_flatten_reg_604.read();
        exitcond_flatten_reg_604 = exitcond_flatten_fu_231_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        bound_reg_599 = bound_fu_558_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_231_p2.read(), ap_const_lv1_0))) {
        tmp_22_reg_618 = tmp_22_fu_303_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_604.read(), ap_const_lv1_0))) {
        tmp_24_cast_reg_628 = tmp_24_cast_fu_315_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter5.read(), ap_const_lv1_0)) {
        tmp_25_reg_689 = tmp_24_fu_409_p2.read().range(15, 8);
        tmp_30_reg_694 = tmp_29_fu_463_p2.read().range(15, 8);
        tmp_35_reg_699 = tmp_34_fu_515_p2.read().range(15, 8);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_231_p2.read(), ap_const_lv1_0))) {
        tmp_mid2_v_reg_613 = tmp_mid2_v_fu_261_p3.read();
    }
}

void yuv_filter_rgb2yuv::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_ap_return_0() {
    ap_return_0 = out_width.read();
}

void yuv_filter_rgb2yuv::thread_ap_return_1() {
    ap_return_1 = out_height.read();
}

void yuv_filter_rgb2yuv::thread_ap_sig_20() {
    ap_sig_20 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void yuv_filter_rgb2yuv::thread_ap_sig_379() {
    ap_sig_379 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void yuv_filter_rgb2yuv::thread_ap_sig_91() {
    ap_sig_91 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void yuv_filter_rgb2yuv::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_91.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_ap_sig_cseq_ST_st11_fsm_2() {
    if (ap_sig_379.read()) {
        ap_sig_cseq_ST_st11_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_2 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_20.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_bound_fu_558_p0() {
    bound_fu_558_p0 =  (sc_lv<16>) (bound_fu_558_p00.read());
}

void yuv_filter_rgb2yuv::thread_bound_fu_558_p00() {
    bound_fu_558_p00 = esl_zext<32,16>(out_height.read());
}

void yuv_filter_rgb2yuv::thread_bound_fu_558_p1() {
    bound_fu_558_p1 =  (sc_lv<16>) (bound_fu_558_p10.read());
}

void yuv_filter_rgb2yuv::thread_bound_fu_558_p10() {
    bound_fu_558_p10 = esl_zext<32,16>(out_width.read());
}

void yuv_filter_rgb2yuv::thread_exitcond9_fu_248_p2() {
    exitcond9_fu_248_p2 = (!y_reg_212.read().is_01() || !out_height.read().is_01())? sc_lv<1>(): sc_lv<1>(y_reg_212.read() == out_height.read());
}

void yuv_filter_rgb2yuv::thread_exitcond_flatten_fu_231_p2() {
    exitcond_flatten_fu_231_p2 = (!indvar_flatten_reg_190.read().is_01() || !bound_reg_599.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_190.read() == bound_reg_599.read());
}

void yuv_filter_rgb2yuv::thread_grp_fu_564_p0() {
    grp_fu_564_p0 =  (sc_lv<8>) (ap_const_lv16_FFA2);
}

void yuv_filter_rgb2yuv::thread_grp_fu_564_p1() {
    grp_fu_564_p1 =  (sc_lv<8>) (tmp_35_cast1_reg_674.read());
}

void yuv_filter_rgb2yuv::thread_grp_fu_571_p0() {
    grp_fu_571_p0 =  (sc_lv<7>) (ap_const_lv15_7FDA);
}

void yuv_filter_rgb2yuv::thread_grp_fu_571_p1() {
    grp_fu_571_p1 =  (sc_lv<8>) (grp_fu_571_p10.read());
}

void yuv_filter_rgb2yuv::thread_grp_fu_571_p10() {
    grp_fu_571_p10 = esl_zext<15,8>(ap_reg_ppstg_R_reg_651_pp0_iter5.read());
}

void yuv_filter_rgb2yuv::thread_grp_fu_579_p0() {
    grp_fu_579_p0 =  (sc_lv<6>) (ap_const_lv13_19);
}

void yuv_filter_rgb2yuv::thread_grp_fu_579_p1() {
    grp_fu_579_p1 =  (sc_lv<8>) (grp_fu_579_p10.read());
}

void yuv_filter_rgb2yuv::thread_grp_fu_579_p10() {
    grp_fu_579_p10 = esl_zext<13,8>(B_reg_666.read());
}

void yuv_filter_rgb2yuv::thread_grp_fu_579_p2() {
    grp_fu_579_p2 =  (sc_lv<9>) (grp_fu_579_p20.read());
}

void yuv_filter_rgb2yuv::thread_grp_fu_579_p20() {
    grp_fu_579_p20 = esl_zext<13,9>(tmp4_fu_396_p2.read());
}

void yuv_filter_rgb2yuv::thread_in_channels_ch1_address0() {
    in_channels_ch1_address0 =  (sc_lv<22>) (tmp_24_cast_fu_315_p1.read());
}

void yuv_filter_rgb2yuv::thread_in_channels_ch1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        in_channels_ch1_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch1_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_in_channels_ch2_address0() {
    in_channels_ch2_address0 =  (sc_lv<22>) (tmp_24_cast_fu_315_p1.read());
}

void yuv_filter_rgb2yuv::thread_in_channels_ch2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        in_channels_ch2_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch2_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_in_channels_ch3_address0() {
    in_channels_ch3_address0 =  (sc_lv<22>) (tmp_24_cast_reg_628.read());
}

void yuv_filter_rgb2yuv::thread_in_channels_ch3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) {
        in_channels_ch3_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch3_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_indvar_flatten_next_fu_236_p2() {
    indvar_flatten_next_fu_236_p2 = (!indvar_flatten_reg_190.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(indvar_flatten_reg_190.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void yuv_filter_rgb2yuv::thread_out_channels_ch1_address0() {
    out_channels_ch1_address0 =  (sc_lv<22>) (ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter6.read());
}

void yuv_filter_rgb2yuv::thread_out_channels_ch1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it8.read()))) {
        out_channels_ch1_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch1_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_out_channels_ch1_d0() {
    out_channels_ch1_d0 = (!ap_const_lv8_10.is_01() || !tmp_25_reg_689.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_10) + sc_biguint<8>(tmp_25_reg_689.read()));
}

void yuv_filter_rgb2yuv::thread_out_channels_ch1_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()) && 
          esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter6.read(), ap_const_lv1_0)))) {
        out_channels_ch1_we0 = ap_const_logic_1;
    } else {
        out_channels_ch1_we0 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_out_channels_ch2_address0() {
    out_channels_ch2_address0 =  (sc_lv<22>) (ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter6.read());
}

void yuv_filter_rgb2yuv::thread_out_channels_ch2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it8.read()))) {
        out_channels_ch2_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch2_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_out_channels_ch2_d0() {
    out_channels_ch2_d0 = (tmp_30_reg_694.read() ^ ap_const_lv8_80);
}

void yuv_filter_rgb2yuv::thread_out_channels_ch2_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()) && 
          esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter6.read(), ap_const_lv1_0)))) {
        out_channels_ch2_we0 = ap_const_logic_1;
    } else {
        out_channels_ch2_we0 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_out_channels_ch3_address0() {
    out_channels_ch3_address0 =  (sc_lv<22>) (ap_reg_ppstg_tmp_24_cast_reg_628_pp0_iter6.read());
}

void yuv_filter_rgb2yuv::thread_out_channels_ch3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it8.read()))) {
        out_channels_ch3_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch3_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_out_channels_ch3_d0() {
    out_channels_ch3_d0 = (tmp_35_reg_699.read() ^ ap_const_lv8_80);
}

void yuv_filter_rgb2yuv::thread_out_channels_ch3_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()) && 
          esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_604_pp0_iter6.read(), ap_const_lv1_0)))) {
        out_channels_ch3_we0 = ap_const_logic_1;
    } else {
        out_channels_ch3_we0 = ap_const_logic_0;
    }
}

void yuv_filter_rgb2yuv::thread_p_neg_cast_fu_484_p1() {
    p_neg_cast_fu_484_p1 = esl_sext<14,13>(p_neg_fu_478_p2.read());
}

void yuv_filter_rgb2yuv::thread_p_neg_fu_478_p2() {
    p_neg_fu_478_p2 = (!ap_const_lv13_0.is_01() || !p_shl3_cast9_fu_443_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_biguint<13>(p_shl3_cast9_fu_443_p1.read()));
}

void yuv_filter_rgb2yuv::thread_p_shl1_cast_fu_495_p1() {
    p_shl1_cast_fu_495_p1 = esl_zext<14,9>(p_shl1_fu_488_p3.read());
}

void yuv_filter_rgb2yuv::thread_p_shl1_fu_488_p3() {
    p_shl1_fu_488_p3 = esl_concat<8,1>(B_reg_666.read(), ap_const_lv1_0);
}

void yuv_filter_rgb2yuv::thread_p_shl2_cast_fu_432_p1() {
    p_shl2_cast_fu_432_p1 = esl_zext<16,15>(p_shl2_fu_425_p3.read());
}

void yuv_filter_rgb2yuv::thread_p_shl2_fu_425_p3() {
    p_shl2_fu_425_p3 = esl_concat<8,7>(B_reg_666.read(), ap_const_lv7_0);
}

void yuv_filter_rgb2yuv::thread_p_shl3_cast9_fu_443_p1() {
    p_shl3_cast9_fu_443_p1 = esl_zext<13,12>(p_shl3_fu_436_p3.read());
}

void yuv_filter_rgb2yuv::thread_p_shl3_cast_fu_447_p1() {
    p_shl3_cast_fu_447_p1 = esl_zext<16,12>(p_shl3_fu_436_p3.read());
}

void yuv_filter_rgb2yuv::thread_p_shl3_fu_436_p3() {
    p_shl3_fu_436_p3 = esl_concat<8,4>(B_reg_666.read(), ap_const_lv4_0);
}

void yuv_filter_rgb2yuv::thread_p_shl4_cast_fu_373_p1() {
    p_shl4_cast_fu_373_p1 = esl_zext<16,15>(p_shl4_fu_366_p3.read());
}

void yuv_filter_rgb2yuv::thread_p_shl4_fu_366_p3() {
    p_shl4_fu_366_p3 = esl_concat<8,7>(ap_reg_ppstg_G_reg_659_pp0_iter5.read(), ap_const_lv7_0);
}

void yuv_filter_rgb2yuv::thread_p_shl5_cast_fu_348_p1() {
    p_shl5_cast_fu_348_p1 = esl_zext<15,14>(p_shl5_fu_341_p3.read());
}

void yuv_filter_rgb2yuv::thread_p_shl5_fu_341_p3() {
    p_shl5_fu_341_p3 = esl_concat<8,6>(ap_reg_ppstg_R_reg_651_pp0_iter5.read(), ap_const_lv6_0);
}

void yuv_filter_rgb2yuv::thread_p_shl6_cast_fu_359_p1() {
    p_shl6_cast_fu_359_p1 = esl_zext<15,9>(p_shl6_fu_352_p3.read());
}

void yuv_filter_rgb2yuv::thread_p_shl6_fu_352_p3() {
    p_shl6_fu_352_p3 = esl_concat<8,1>(ap_reg_ppstg_R_reg_651_pp0_iter5.read(), ap_const_lv1_0);
}

void yuv_filter_rgb2yuv::thread_p_shl7_cast_fu_285_p3() {
    p_shl7_cast_fu_285_p3 = esl_concat<15,8>(tmp_20_fu_281_p1.read(), ap_const_lv8_0);
}

void yuv_filter_rgb2yuv::thread_p_shl_cast_fu_273_p3() {
    p_shl_cast_fu_273_p3 = esl_concat<13,10>(tmp_fu_269_p1.read(), ap_const_lv10_0);
}

void yuv_filter_rgb2yuv::thread_tmp1_fu_390_p2() {
    tmp1_fu_390_p2 = (!tmp2_cast_fu_386_p1.read().is_01() || !p_shl4_cast_fu_373_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp2_cast_fu_386_p1.read()) + sc_biguint<16>(p_shl4_cast_fu_373_p1.read()));
}

void yuv_filter_rgb2yuv::thread_tmp2_cast_fu_386_p1() {
    tmp2_cast_fu_386_p1 = esl_zext<16,15>(tmp2_fu_380_p2.read());
}

void yuv_filter_rgb2yuv::thread_tmp2_fu_380_p2() {
    tmp2_fu_380_p2 = (!p_shl6_cast_fu_359_p1.read().is_01() || !p_shl5_cast_fu_348_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl6_cast_fu_359_p1.read()) + sc_biguint<15>(p_shl5_cast_fu_348_p1.read()));
}

void yuv_filter_rgb2yuv::thread_tmp3_cast_fu_406_p1() {
    tmp3_cast_fu_406_p1 = esl_zext<16,13>(grp_fu_579_p3.read());
}

void yuv_filter_rgb2yuv::thread_tmp4_fu_396_p2() {
    tmp4_fu_396_p2 = (!ap_const_lv9_80.is_01() || !tmp_35_cast2_fu_363_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_80) + sc_biguint<9>(tmp_35_cast2_fu_363_p1.read()));
}

void yuv_filter_rgb2yuv::thread_tmp6_fu_457_p2() {
    tmp6_fu_457_p2 = (!ap_const_lv16_80.is_01() || !tmp_28_fu_451_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_80) + sc_biguint<16>(tmp_28_fu_451_p2.read()));
}

void yuv_filter_rgb2yuv::thread_tmp8_cast_fu_511_p1() {
    tmp8_cast_fu_511_p1 = esl_sext<16,14>(tmp8_fu_505_p2.read());
}

void yuv_filter_rgb2yuv::thread_tmp8_fu_505_p2() {
    tmp8_fu_505_p2 = (!ap_const_lv14_80.is_01() || !tmp_33_fu_499_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_80) + sc_biguint<14>(tmp_33_fu_499_p2.read()));
}

void yuv_filter_rgb2yuv::thread_tmp_20_fu_281_p1() {
    tmp_20_fu_281_p1 = tmp_mid2_v_fu_261_p3.read().range(15-1, 0);
}

void yuv_filter_rgb2yuv::thread_tmp_22_fu_303_p2() {
    tmp_22_fu_303_p2 = (!tmp_cast_fu_299_p1.read().is_01() || !tmp_s_fu_293_p2.read().is_01())? sc_lv<23>(): (sc_biguint<23>(tmp_cast_fu_299_p1.read()) + sc_biguint<23>(tmp_s_fu_293_p2.read()));
}

void yuv_filter_rgb2yuv::thread_tmp_24_cast_fu_315_p1() {
    tmp_24_cast_fu_315_p1 = esl_zext<64,23>(tmp_22_reg_618.read());
}

void yuv_filter_rgb2yuv::thread_tmp_24_fu_409_p2() {
    tmp_24_fu_409_p2 = (!tmp3_cast_fu_406_p1.read().is_01() || !tmp1_fu_390_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp3_cast_fu_406_p1.read()) + sc_biguint<16>(tmp1_fu_390_p2.read()));
}

void yuv_filter_rgb2yuv::thread_tmp_27_fu_326_p1() {
    tmp_27_fu_326_p1 =  (sc_lv<8>) (tmp_27_fu_326_p10.read());
}

void yuv_filter_rgb2yuv::thread_tmp_27_fu_326_p10() {
    tmp_27_fu_326_p10 = esl_zext<16,8>(G_reg_659.read());
}

void yuv_filter_rgb2yuv::thread_tmp_27_fu_326_p2() {
    tmp_27_fu_326_p2 = (!ap_const_lv16_FFB6.is_01() || !tmp_27_fu_326_p1.read().is_01())? sc_lv<16>(): sc_bigint<16>(ap_const_lv16_FFB6) * sc_biguint<8>(tmp_27_fu_326_p1.read());
}

void yuv_filter_rgb2yuv::thread_tmp_28_fu_451_p2() {
    tmp_28_fu_451_p2 = (!p_shl2_cast_fu_432_p1.read().is_01() || !p_shl3_cast_fu_447_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(p_shl2_cast_fu_432_p1.read()) - sc_biguint<16>(p_shl3_cast_fu_447_p1.read()));
}

void yuv_filter_rgb2yuv::thread_tmp_29_fu_463_p2() {
    tmp_29_fu_463_p2 = (!tmp6_fu_457_p2.read().is_01() || !grp_fu_571_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp6_fu_457_p2.read()) + sc_bigint<16>(grp_fu_571_p3.read()));
}

void yuv_filter_rgb2yuv::thread_tmp_31_fu_332_p1() {
    tmp_31_fu_332_p1 =  (sc_lv<8>) (tmp_31_fu_332_p10.read());
}

void yuv_filter_rgb2yuv::thread_tmp_31_fu_332_p10() {
    tmp_31_fu_332_p10 = esl_zext<16,8>(R_reg_651.read());
}

void yuv_filter_rgb2yuv::thread_tmp_31_fu_332_p2() {
    tmp_31_fu_332_p2 = (!ap_const_lv16_7A.is_01() || !tmp_31_fu_332_p1.read().is_01())? sc_lv<16>(): sc_biguint<16>(ap_const_lv16_7A) * sc_biguint<8>(tmp_31_fu_332_p1.read());
}

void yuv_filter_rgb2yuv::thread_tmp_33_fu_499_p2() {
    tmp_33_fu_499_p2 = (!p_neg_cast_fu_484_p1.read().is_01() || !p_shl1_cast_fu_495_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(p_neg_cast_fu_484_p1.read()) - sc_biguint<14>(p_shl1_cast_fu_495_p1.read()));
}

void yuv_filter_rgb2yuv::thread_tmp_34_fu_515_p2() {
    tmp_34_fu_515_p2 = (!tmp8_cast_fu_511_p1.read().is_01() || !grp_fu_564_p3.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp8_cast_fu_511_p1.read()) + sc_bigint<16>(grp_fu_564_p3.read()));
}

void yuv_filter_rgb2yuv::thread_tmp_35_cast1_fu_323_p1() {
    tmp_35_cast1_fu_323_p1 = esl_zext<16,8>(G_reg_659.read());
}

void yuv_filter_rgb2yuv::thread_tmp_35_cast2_fu_363_p1() {
    tmp_35_cast2_fu_363_p1 = esl_zext<9,8>(ap_reg_ppstg_G_reg_659_pp0_iter5.read());
}

void yuv_filter_rgb2yuv::thread_tmp_cast_fu_299_p1() {
    tmp_cast_fu_299_p1 = esl_zext<23,16>(y_mid2_fu_253_p3.read());
}

void yuv_filter_rgb2yuv::thread_tmp_fu_269_p1() {
    tmp_fu_269_p1 = tmp_mid2_v_fu_261_p3.read().range(13-1, 0);
}

void yuv_filter_rgb2yuv::thread_tmp_mid2_v_fu_261_p3() {
    tmp_mid2_v_fu_261_p3 = (!exitcond9_fu_248_p2.read()[0].is_01())? sc_lv<16>(): ((exitcond9_fu_248_p2.read()[0].to_bool())? x_2_fu_242_p2.read(): x_phi_fu_205_p4.read());
}

void yuv_filter_rgb2yuv::thread_tmp_s_fu_293_p2() {
    tmp_s_fu_293_p2 = (!p_shl_cast_fu_273_p3.read().is_01() || !p_shl7_cast_fu_285_p3.read().is_01())? sc_lv<23>(): (sc_biguint<23>(p_shl_cast_fu_273_p3.read()) + sc_biguint<23>(p_shl7_cast_fu_285_p3.read()));
}

void yuv_filter_rgb2yuv::thread_x_2_fu_242_p2() {
    x_2_fu_242_p2 = (!ap_const_lv16_1.is_01() || !x_phi_fu_205_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_1) + sc_biguint<16>(x_phi_fu_205_p4.read()));
}

void yuv_filter_rgb2yuv::thread_x_phi_fu_205_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_604.read(), ap_const_lv1_0))) {
        x_phi_fu_205_p4 = tmp_mid2_v_reg_613.read();
    } else {
        x_phi_fu_205_p4 = x_reg_201.read();
    }
}

void yuv_filter_rgb2yuv::thread_y_2_fu_309_p2() {
    y_2_fu_309_p2 = (!ap_const_lv16_1.is_01() || !y_mid2_fu_253_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_1) + sc_biguint<16>(y_mid2_fu_253_p3.read()));
}

void yuv_filter_rgb2yuv::thread_y_mid2_fu_253_p3() {
    y_mid2_fu_253_p3 = (!exitcond9_fu_248_p2.read()[0].is_01())? sc_lv<16>(): ((exitcond9_fu_248_p2.read()[0].to_bool())? ap_const_lv16_0: y_reg_212.read());
}

void yuv_filter_rgb2yuv::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it8.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten_fu_231_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten_fu_231_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_st11_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st11_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

