// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dct_dct_1d2_HH_
#define _dct_dct_1d2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dct_mac_muladd_16s_15s_29s_29_1.h"
#include "dct_mac_muladd_16s_15s_14ns_29_1.h"
#include "dct_mac_muladd_16s_14ns_29s_29_1.h"
#include "dct_mul_mul_16s_15s_29_1.h"
#include "dct_dct_1d2_dct_coeff_table_0.h"
#include "dct_dct_1d2_dct_coeff_table_1.h"
#include "dct_dct_1d2_dct_coeff_table_2.h"
#include "dct_dct_1d2_dct_coeff_table_3.h"
#include "dct_dct_1d2_dct_coeff_table_4.h"
#include "dct_dct_1d2_dct_coeff_table_5.h"
#include "dct_dct_1d2_dct_coeff_table_6.h"
#include "dct_dct_1d2_dct_coeff_table_7.h"

namespace ap_rtl {

struct dct_dct_1d2 : public sc_module {
    // Port declarations 18
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<6> > src_address0;
    sc_out< sc_logic > src_ce0;
    sc_in< sc_lv<16> > src_q0;
    sc_out< sc_lv<6> > src_address1;
    sc_out< sc_logic > src_ce1;
    sc_in< sc_lv<16> > src_q1;
    sc_in< sc_lv<4> > tmp_2;
    sc_out< sc_lv<6> > dst_address0;
    sc_out< sc_logic > dst_ce0;
    sc_out< sc_logic > dst_we0;
    sc_out< sc_lv<16> > dst_d0;
    sc_in< sc_lv<4> > tmp_21;


    // Module declarations
    dct_dct_1d2(sc_module_name name);
    SC_HAS_PROCESS(dct_dct_1d2);

    ~dct_dct_1d2();

    sc_trace_file* mVcdFile;

    dct_dct_1d2_dct_coeff_table_0* dct_coeff_table_0_U;
    dct_dct_1d2_dct_coeff_table_1* dct_coeff_table_1_U;
    dct_dct_1d2_dct_coeff_table_2* dct_coeff_table_2_U;
    dct_dct_1d2_dct_coeff_table_3* dct_coeff_table_3_U;
    dct_dct_1d2_dct_coeff_table_4* dct_coeff_table_4_U;
    dct_dct_1d2_dct_coeff_table_5* dct_coeff_table_5_U;
    dct_dct_1d2_dct_coeff_table_6* dct_coeff_table_6_U;
    dct_dct_1d2_dct_coeff_table_7* dct_coeff_table_7_U;
    dct_mac_muladd_16s_15s_29s_29_1<1,1,16,15,29,29>* dct_mac_muladd_16s_15s_29s_29_1_U0;
    dct_mac_muladd_16s_15s_14ns_29_1<1,1,16,15,14,29>* dct_mac_muladd_16s_15s_14ns_29_1_U1;
    dct_mac_muladd_16s_15s_29s_29_1<1,1,16,15,29,29>* dct_mac_muladd_16s_15s_29s_29_1_U2;
    dct_mac_muladd_16s_15s_29s_29_1<1,1,16,15,29,29>* dct_mac_muladd_16s_15s_29s_29_1_U3;
    dct_mac_muladd_16s_14ns_29s_29_1<1,1,16,14,29,29>* dct_mac_muladd_16s_14ns_29s_29_1_U4;
    dct_mul_mul_16s_15s_29_1<1,1,16,15,29>* dct_mul_mul_16s_15s_29_1_U5;
    dct_mul_mul_16s_15s_29_1<1,1,16,15,29>* dct_mul_mul_16s_15s_29_1_U6;
    dct_mul_mul_16s_15s_29_1<1,1,16,15,29>* dct_mul_mul_16s_15s_29_1_U7;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_23;
    sc_signal< sc_lv<3> > dct_coeff_table_0_address0;
    sc_signal< sc_logic > dct_coeff_table_0_ce0;
    sc_signal< sc_lv<14> > dct_coeff_table_0_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_1_address0;
    sc_signal< sc_logic > dct_coeff_table_1_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_1_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_2_address0;
    sc_signal< sc_logic > dct_coeff_table_2_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_2_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_3_address0;
    sc_signal< sc_logic > dct_coeff_table_3_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_3_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_4_address0;
    sc_signal< sc_logic > dct_coeff_table_4_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_4_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_5_address0;
    sc_signal< sc_logic > dct_coeff_table_5_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_5_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_6_address0;
    sc_signal< sc_logic > dct_coeff_table_6_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_6_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_7_address0;
    sc_signal< sc_logic > dct_coeff_table_7_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_7_q0;
    sc_signal< sc_lv<4> > k_reg_269;
    sc_signal< sc_lv<16> > reg_280;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg1_fsm_2;
    sc_signal< bool > ap_sig_110;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_lv<1> > exitcond1_reg_630;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg2_fsm_3;
    sc_signal< bool > ap_sig_126;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg3_fsm_4;
    sc_signal< bool > ap_sig_136;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_1;
    sc_signal< bool > ap_sig_146;
    sc_signal< sc_lv<16> > reg_284;
    sc_signal< sc_lv<8> > tmp_17_cast_fu_296_p1;
    sc_signal< sc_lv<8> > tmp_17_cast_reg_585;
    sc_signal< sc_lv<6> > src_addr_reg_590;
    sc_signal< sc_lv<6> > src_addr_1_reg_595;
    sc_signal< sc_lv<6> > src_addr_2_reg_600;
    sc_signal< sc_lv<6> > src_addr_3_reg_605;
    sc_signal< sc_lv<6> > src_addr_4_reg_610;
    sc_signal< sc_lv<6> > src_addr_5_reg_615;
    sc_signal< sc_lv<6> > src_addr_6_reg_620;
    sc_signal< sc_lv<6> > src_addr_7_reg_625;
    sc_signal< sc_lv<1> > exitcond1_fu_418_p2;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond1_reg_630_pp0_iter1;
    sc_signal< sc_lv<4> > k_1_fu_424_p2;
    sc_signal< sc_lv<4> > k_1_reg_634;
    sc_signal< sc_lv<64> > tmp_fu_430_p1;
    sc_signal< sc_lv<64> > tmp_reg_639;
    sc_signal< sc_lv<8> > tmp_24_fu_440_p2;
    sc_signal< sc_lv<8> > tmp_24_reg_649;
    sc_signal< sc_lv<8> > ap_reg_ppstg_tmp_24_reg_649_pp0_iter1;
    sc_signal< sc_lv<15> > dct_coeff_table_1_load_reg_669;
    sc_signal< sc_lv<15> > dct_coeff_table_3_load_reg_679;
    sc_signal< sc_lv<14> > dct_coeff_table_0_load_reg_704;
    sc_signal< sc_lv<29> > tmp_10_1_fu_579_p2;
    sc_signal< sc_lv<29> > tmp_10_1_reg_709;
    sc_signal< sc_lv<15> > dct_coeff_table_2_load_reg_714;
    sc_signal< sc_lv<29> > tmp_10_3_fu_573_p2;
    sc_signal< sc_lv<29> > tmp_10_3_reg_719;
    sc_signal< sc_lv<15> > dct_coeff_table_4_load_reg_724;
    sc_signal< sc_lv<15> > dct_coeff_table_5_load_reg_729;
    sc_signal< sc_lv<15> > dct_coeff_table_6_load_reg_734;
    sc_signal< sc_lv<15> > dct_coeff_table_7_load_reg_739;
    sc_signal< sc_lv<29> > tmp_10_5_fu_567_p2;
    sc_signal< sc_lv<29> > tmp_10_5_reg_744;
    sc_signal< sc_lv<29> > grp_fu_560_p3;
    sc_signal< sc_lv<29> > tmp2_reg_749;
    sc_signal< sc_lv<29> > tmp1_fu_487_p2;
    sc_signal< sc_lv<29> > tmp1_reg_754;
    sc_signal< sc_lv<29> > grp_fu_545_p3;
    sc_signal< sc_lv<29> > tmp5_reg_759;
    sc_signal< sc_lv<29> > grp_fu_529_p3;
    sc_signal< sc_lv<29> > tmp6_reg_764;
    sc_signal< sc_lv<4> > k_phi_fu_273_p4;
    sc_signal< sc_lv<64> > tmp_8_fu_308_p1;
    sc_signal< sc_lv<64> > tmp_10_fu_319_p3;
    sc_signal< sc_lv<64> > tmp_12_fu_334_p3;
    sc_signal< sc_lv<64> > tmp_14_fu_349_p3;
    sc_signal< sc_lv<64> > tmp_16_fu_364_p3;
    sc_signal< sc_lv<64> > tmp_18_fu_379_p3;
    sc_signal< sc_lv<64> > tmp_20_fu_394_p3;
    sc_signal< sc_lv<64> > tmp_23_fu_409_p3;
    sc_signal< sc_lv<64> > tmp_35_cast_fu_505_p1;
    sc_signal< sc_lv<7> > tmp_5_fu_288_p3;
    sc_signal< sc_lv<7> > tmp_6_fu_300_p3;
    sc_signal< sc_lv<7> > tmp_9_fu_313_p2;
    sc_signal< sc_lv<7> > tmp_11_fu_328_p2;
    sc_signal< sc_lv<7> > tmp_13_fu_343_p2;
    sc_signal< sc_lv<7> > tmp_15_fu_358_p2;
    sc_signal< sc_lv<7> > tmp_17_fu_373_p2;
    sc_signal< sc_lv<7> > tmp_19_fu_388_p2;
    sc_signal< sc_lv<7> > tmp_22_fu_403_p2;
    sc_signal< sc_lv<8> > tmp_cast_fu_436_p1;
    sc_signal< sc_lv<29> > grp_fu_552_p3;
    sc_signal< sc_lv<29> > tmp4_fu_509_p2;
    sc_signal< sc_lv<29> > tmp_s_fu_513_p2;
    sc_signal< sc_lv<29> > grp_fu_536_p3;
    sc_signal< sc_lv<14> > grp_fu_536_p2;
    sc_signal< sc_lv<14> > grp_fu_560_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_5;
    sc_signal< bool > ap_sig_453;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    sc_signal< sc_lv<29> > grp_fu_560_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_st1_fsm_0;
    static const sc_lv<6> ap_ST_pp0_stg0_fsm_1;
    static const sc_lv<6> ap_ST_pp0_stg1_fsm_2;
    static const sc_lv<6> ap_ST_pp0_stg2_fsm_3;
    static const sc_lv<6> ap_ST_pp0_stg3_fsm_4;
    static const sc_lv<6> ap_ST_st9_fsm_5;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<57> ap_const_lv57_0;
    static const sc_lv<7> ap_const_lv7_2;
    static const sc_lv<7> ap_const_lv7_3;
    static const sc_lv<7> ap_const_lv7_4;
    static const sc_lv<7> ap_const_lv7_5;
    static const sc_lv<7> ap_const_lv7_6;
    static const sc_lv<7> ap_const_lv7_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<29> ap_const_lv29_1000;
    static const sc_lv<32> ap_const_lv32_5;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_110();
    void thread_ap_sig_126();
    void thread_ap_sig_136();
    void thread_ap_sig_146();
    void thread_ap_sig_23();
    void thread_ap_sig_453();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_1();
    void thread_ap_sig_cseq_ST_pp0_stg1_fsm_2();
    void thread_ap_sig_cseq_ST_pp0_stg2_fsm_3();
    void thread_ap_sig_cseq_ST_pp0_stg3_fsm_4();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st9_fsm_5();
    void thread_dct_coeff_table_0_address0();
    void thread_dct_coeff_table_0_ce0();
    void thread_dct_coeff_table_1_address0();
    void thread_dct_coeff_table_1_ce0();
    void thread_dct_coeff_table_2_address0();
    void thread_dct_coeff_table_2_ce0();
    void thread_dct_coeff_table_3_address0();
    void thread_dct_coeff_table_3_ce0();
    void thread_dct_coeff_table_4_address0();
    void thread_dct_coeff_table_4_ce0();
    void thread_dct_coeff_table_5_address0();
    void thread_dct_coeff_table_5_ce0();
    void thread_dct_coeff_table_6_address0();
    void thread_dct_coeff_table_6_ce0();
    void thread_dct_coeff_table_7_address0();
    void thread_dct_coeff_table_7_ce0();
    void thread_dst_address0();
    void thread_dst_ce0();
    void thread_dst_d0();
    void thread_dst_we0();
    void thread_exitcond1_fu_418_p2();
    void thread_grp_fu_536_p2();
    void thread_grp_fu_560_p1();
    void thread_grp_fu_560_p10();
    void thread_k_1_fu_424_p2();
    void thread_k_phi_fu_273_p4();
    void thread_src_address0();
    void thread_src_address1();
    void thread_src_ce0();
    void thread_src_ce1();
    void thread_tmp1_fu_487_p2();
    void thread_tmp4_fu_509_p2();
    void thread_tmp_10_fu_319_p3();
    void thread_tmp_11_fu_328_p2();
    void thread_tmp_12_fu_334_p3();
    void thread_tmp_13_fu_343_p2();
    void thread_tmp_14_fu_349_p3();
    void thread_tmp_15_fu_358_p2();
    void thread_tmp_16_fu_364_p3();
    void thread_tmp_17_cast_fu_296_p1();
    void thread_tmp_17_fu_373_p2();
    void thread_tmp_18_fu_379_p3();
    void thread_tmp_19_fu_388_p2();
    void thread_tmp_20_fu_394_p3();
    void thread_tmp_22_fu_403_p2();
    void thread_tmp_23_fu_409_p3();
    void thread_tmp_24_fu_440_p2();
    void thread_tmp_35_cast_fu_505_p1();
    void thread_tmp_5_fu_288_p3();
    void thread_tmp_6_fu_300_p3();
    void thread_tmp_8_fu_308_p1();
    void thread_tmp_9_fu_313_p2();
    void thread_tmp_cast_fu_436_p1();
    void thread_tmp_fu_430_p1();
    void thread_tmp_s_fu_513_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
