// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _yuv_filter_yuv2rgb_HH_
#define _yuv_filter_yuv2rgb_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "yuv_filter_mac_muladd_8s_8s_17ns_17_1.h"
#include "yuv_filter_ama_addmuladd_5s_8ns_10ns_9ns_18_1.h"
#include "yuv_filter_mac_muladd_10ns_8s_18s_18_1.h"

namespace ap_rtl {

struct yuv_filter_yuv2rgb : public sc_module {
    // Port declarations 31
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<22> > in_channels_ch1_address0;
    sc_out< sc_logic > in_channels_ch1_ce0;
    sc_in< sc_lv<8> > in_channels_ch1_q0;
    sc_out< sc_lv<22> > in_channels_ch2_address0;
    sc_out< sc_logic > in_channels_ch2_ce0;
    sc_in< sc_lv<8> > in_channels_ch2_q0;
    sc_out< sc_lv<22> > in_channels_ch3_address0;
    sc_out< sc_logic > in_channels_ch3_ce0;
    sc_in< sc_lv<8> > in_channels_ch3_q0;
    sc_in< sc_lv<16> > out_width;
    sc_in< sc_lv<16> > out_height;
    sc_out< sc_lv<22> > out_channels_ch1_address0;
    sc_out< sc_logic > out_channels_ch1_ce0;
    sc_out< sc_logic > out_channels_ch1_we0;
    sc_out< sc_lv<8> > out_channels_ch1_d0;
    sc_out< sc_lv<22> > out_channels_ch2_address0;
    sc_out< sc_logic > out_channels_ch2_ce0;
    sc_out< sc_logic > out_channels_ch2_we0;
    sc_out< sc_lv<8> > out_channels_ch2_d0;
    sc_out< sc_lv<22> > out_channels_ch3_address0;
    sc_out< sc_logic > out_channels_ch3_ce0;
    sc_out< sc_logic > out_channels_ch3_we0;
    sc_out< sc_lv<8> > out_channels_ch3_d0;
    sc_out< sc_lv<16> > ap_return_0;
    sc_out< sc_lv<16> > ap_return_1;


    // Module declarations
    yuv_filter_yuv2rgb(sc_module_name name);
    SC_HAS_PROCESS(yuv_filter_yuv2rgb);

    ~yuv_filter_yuv2rgb();

    sc_trace_file* mVcdFile;

    yuv_filter_mac_muladd_8s_8s_17ns_17_1<1,1,8,8,17,17>* yuv_filter_mac_muladd_8s_8s_17ns_17_1_U11;
    yuv_filter_ama_addmuladd_5s_8ns_10ns_9ns_18_1<1,1,5,8,10,9,18>* yuv_filter_ama_addmuladd_5s_8ns_10ns_9ns_18_1_U12;
    yuv_filter_mac_muladd_10ns_8s_18s_18_1<1,1,10,8,18,18>* yuv_filter_mac_muladd_10ns_8s_18s_18_1_U13;
    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_27;
    sc_signal< sc_lv<16> > x_1_fu_219_p2;
    sc_signal< sc_lv<16> > x_1_reg_574;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_90;
    sc_signal< sc_lv<23> > tmp_s_fu_249_p2;
    sc_signal< sc_lv<23> > tmp_s_reg_579;
    sc_signal< sc_lv<1> > exitcond1_fu_214_p2;
    sc_signal< sc_lv<16> > y_1_fu_270_p2;
    sc_signal< sc_lv<16> > y_1_reg_587;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_105;
    sc_signal< sc_lv<64> > tmp_21_cast_fu_285_p1;
    sc_signal< sc_lv<64> > tmp_21_cast_reg_592;
    sc_signal< sc_lv<1> > exitcond_fu_265_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_123;
    sc_signal< sc_lv<8> > Y_reg_615;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_131;
    sc_signal< sc_lv<8> > V_reg_620;
    sc_signal< sc_lv<8> > D_fu_294_p2;
    sc_signal< sc_lv<8> > D_reg_625;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_141;
    sc_signal< sc_lv<8> > E_fu_300_p2;
    sc_signal< sc_lv<8> > E_reg_632;
    sc_signal< sc_lv<18> > grp_fu_539_p4;
    sc_signal< sc_lv<18> > tmp_3_reg_637;
    sc_signal< sc_lv<17> > tmp_13_fu_309_p2;
    sc_signal< sc_lv<17> > tmp_13_reg_644;
    sc_signal< sc_lv<8> > R_fu_363_p3;
    sc_signal< sc_lv<8> > R_reg_649;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_156;
    sc_signal< sc_lv<8> > G_fu_430_p3;
    sc_signal< sc_lv<8> > G_reg_654;
    sc_signal< sc_lv<8> > B_fu_523_p3;
    sc_signal< sc_lv<8> > B_reg_659;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_169;
    sc_signal< sc_lv<16> > x_reg_192;
    sc_signal< sc_lv<16> > y_reg_203;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_187;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_195;
    sc_signal< sc_lv<13> > tmp_fu_225_p1;
    sc_signal< sc_lv<15> > tmp_5_fu_237_p1;
    sc_signal< sc_lv<23> > p_shl2_cast_fu_229_p3;
    sc_signal< sc_lv<23> > p_shl3_cast_fu_241_p3;
    sc_signal< sc_lv<23> > tmp_cast_fu_276_p1;
    sc_signal< sc_lv<23> > tmp_6_fu_280_p2;
    sc_signal< sc_lv<8> > tmp_13_fu_309_p1;
    sc_signal< sc_lv<18> > grp_fu_549_p3;
    sc_signal< sc_lv<2> > tmp_8_fu_318_p4;
    sc_signal< sc_lv<1> > icmp_fu_327_p2;
    sc_signal< sc_lv<1> > tmp_10_fu_333_p3;
    sc_signal< sc_lv<1> > tmp_11_fu_357_p2;
    sc_signal< sc_lv<8> > p_phitmp_fu_349_p3;
    sc_signal< sc_lv<8> > phitmp_fu_340_p4;
    sc_signal< sc_lv<17> > grp_fu_531_p3;
    sc_signal< sc_lv<18> > tmp1_cast_fu_374_p1;
    sc_signal< sc_lv<18> > tmp_14_fu_377_p2;
    sc_signal< sc_lv<2> > tmp_15_fu_382_p4;
    sc_signal< sc_lv<1> > icmp9_fu_392_p2;
    sc_signal< sc_lv<1> > tmp_16_fu_398_p3;
    sc_signal< sc_lv<1> > tmp_17_fu_424_p2;
    sc_signal< sc_lv<8> > p_phitmp2_fu_416_p3;
    sc_signal< sc_lv<8> > phitmp2_fu_406_p4;
    sc_signal< sc_lv<17> > p_shl_fu_438_p3;
    sc_signal< sc_lv<10> > p_shl1_fu_449_p3;
    sc_signal< sc_lv<18> > p_shl1_cast_fu_456_p1;
    sc_signal< sc_lv<18> > tmp2_fu_460_p2;
    sc_signal< sc_lv<19> > tmp2_cast_fu_465_p1;
    sc_signal< sc_lv<19> > p_shl_cast_fu_445_p1;
    sc_signal< sc_lv<19> > tmp_18_fu_469_p2;
    sc_signal< sc_lv<3> > tmp_19_fu_475_p4;
    sc_signal< sc_lv<1> > icmp1_fu_485_p2;
    sc_signal< sc_lv<1> > tmp_20_fu_491_p3;
    sc_signal< sc_lv<1> > tmp_21_fu_517_p2;
    sc_signal< sc_lv<8> > p_phitmp3_fu_509_p3;
    sc_signal< sc_lv<8> > phitmp3_fu_499_p4;
    sc_signal< sc_lv<8> > grp_fu_531_p0;
    sc_signal< sc_lv<5> > grp_fu_539_p0;
    sc_signal< sc_lv<8> > grp_fu_539_p1;
    sc_signal< sc_lv<10> > grp_fu_539_p2;
    sc_signal< sc_lv<9> > grp_fu_539_p3;
    sc_signal< sc_lv<10> > grp_fu_549_p0;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    sc_signal< sc_lv<9> > grp_fu_539_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_st1_fsm_0;
    static const sc_lv<10> ap_ST_st2_fsm_1;
    static const sc_lv<10> ap_ST_st3_fsm_2;
    static const sc_lv<10> ap_ST_st4_fsm_3;
    static const sc_lv<10> ap_ST_st5_fsm_4;
    static const sc_lv<10> ap_ST_st6_fsm_5;
    static const sc_lv<10> ap_ST_st7_fsm_6;
    static const sc_lv<10> ap_ST_st8_fsm_7;
    static const sc_lv<10> ap_ST_st9_fsm_8;
    static const sc_lv<10> ap_ST_st10_fsm_9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<16> ap_const_lv16_1;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<8> ap_const_lv8_80;
    static const sc_lv<17> ap_const_lv17_1FF30;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<16> ap_const_lv16_FF9C;
    static const sc_lv<9> ap_const_lv9_1F0;
    static const sc_lv<18> ap_const_lv18_12A;
    static const sc_lv<18> ap_const_lv18_80;
    static const sc_lv<18> ap_const_lv18_199;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_B_fu_523_p3();
    void thread_D_fu_294_p2();
    void thread_E_fu_300_p2();
    void thread_G_fu_430_p3();
    void thread_R_fu_363_p3();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_sig_105();
    void thread_ap_sig_123();
    void thread_ap_sig_131();
    void thread_ap_sig_141();
    void thread_ap_sig_156();
    void thread_ap_sig_169();
    void thread_ap_sig_187();
    void thread_ap_sig_195();
    void thread_ap_sig_27();
    void thread_ap_sig_90();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_exitcond1_fu_214_p2();
    void thread_exitcond_fu_265_p2();
    void thread_grp_fu_531_p0();
    void thread_grp_fu_539_p0();
    void thread_grp_fu_539_p1();
    void thread_grp_fu_539_p10();
    void thread_grp_fu_539_p2();
    void thread_grp_fu_539_p3();
    void thread_grp_fu_549_p0();
    void thread_icmp1_fu_485_p2();
    void thread_icmp9_fu_392_p2();
    void thread_icmp_fu_327_p2();
    void thread_in_channels_ch1_address0();
    void thread_in_channels_ch1_ce0();
    void thread_in_channels_ch2_address0();
    void thread_in_channels_ch2_ce0();
    void thread_in_channels_ch3_address0();
    void thread_in_channels_ch3_ce0();
    void thread_out_channels_ch1_address0();
    void thread_out_channels_ch1_ce0();
    void thread_out_channels_ch1_d0();
    void thread_out_channels_ch1_we0();
    void thread_out_channels_ch2_address0();
    void thread_out_channels_ch2_ce0();
    void thread_out_channels_ch2_d0();
    void thread_out_channels_ch2_we0();
    void thread_out_channels_ch3_address0();
    void thread_out_channels_ch3_ce0();
    void thread_out_channels_ch3_d0();
    void thread_out_channels_ch3_we0();
    void thread_p_phitmp2_fu_416_p3();
    void thread_p_phitmp3_fu_509_p3();
    void thread_p_phitmp_fu_349_p3();
    void thread_p_shl1_cast_fu_456_p1();
    void thread_p_shl1_fu_449_p3();
    void thread_p_shl2_cast_fu_229_p3();
    void thread_p_shl3_cast_fu_241_p3();
    void thread_p_shl_cast_fu_445_p1();
    void thread_p_shl_fu_438_p3();
    void thread_phitmp2_fu_406_p4();
    void thread_phitmp3_fu_499_p4();
    void thread_phitmp_fu_340_p4();
    void thread_tmp1_cast_fu_374_p1();
    void thread_tmp2_cast_fu_465_p1();
    void thread_tmp2_fu_460_p2();
    void thread_tmp_10_fu_333_p3();
    void thread_tmp_11_fu_357_p2();
    void thread_tmp_13_fu_309_p1();
    void thread_tmp_13_fu_309_p2();
    void thread_tmp_14_fu_377_p2();
    void thread_tmp_15_fu_382_p4();
    void thread_tmp_16_fu_398_p3();
    void thread_tmp_17_fu_424_p2();
    void thread_tmp_18_fu_469_p2();
    void thread_tmp_19_fu_475_p4();
    void thread_tmp_20_fu_491_p3();
    void thread_tmp_21_cast_fu_285_p1();
    void thread_tmp_21_fu_517_p2();
    void thread_tmp_5_fu_237_p1();
    void thread_tmp_6_fu_280_p2();
    void thread_tmp_8_fu_318_p4();
    void thread_tmp_cast_fu_276_p1();
    void thread_tmp_fu_225_p1();
    void thread_tmp_s_fu_249_p2();
    void thread_x_1_fu_219_p2();
    void thread_y_1_fu_270_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
